#!/usr/bin/env python3
"""Paused RSA challengers for spend-only Stage 1 groups. Editor CSV only.

After file 02. Do not mix with today's Australia Post.
Does not edit frozen winners or Brand. All Ad Status = Paused.
If a group already has 3 enabled RSAs, this is a paused extra — do not Enable a 4th.
"""

from __future__ import annotations

import csv
import json
import re
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
OUT_US = HERE / "04-spend-only-challengers-us.csv"
OUT_AU = HERE / "04-spend-only-challengers-au.csv"
OUT_JSON = HERE / "spend-only-challengers.json"
XRAY_JSON = REPO / "xray" / "data" / "spend-only-challengers.json"

HL_MAX = 30
DESC_MAX = 90
PATH_MAX = 15
LABEL = "VC_AUG20_CHALLENGER_2026-08-20"

ACCOUNT = {"US": "496-715-1855", "AU": "573-539-1940"}

HEADER = [
    "Account",
    "Row Type",
    "Campaign",
    "Campaign Type",
    "Campaign Status",
    "Budget",
    "Budget type",
    "Bid Strategy Type",
    "Networks",
    "Languages",
    "Location",
    "Location options",
    "Tracking template",
    "Final URL suffix",
    "Ad Group",
    "Ad Group Status",
    "Maximum CPC bid limit",
    "Keyword",
    "Criterion Type",
    "Keyword Status",
    "Ad Status",
    "Ad type",
    "Final URL",
    "Path 1",
    "Path 2",
    *(f"Headline {i}" for i in range(1, 16)),
    *(f"Description {i}" for i in range(1, 5)),
    "Link Text",
    "Description Line 1",
    "Description Line 2",
    "Callout text",
    "Header",
    "Snippet Values",
    "Negative",
    "Labels",
    "Comment",
]


def _len_ok(s: str, max_len: int) -> bool:
    m = re.fullmatch(r"\{(?:KeyWord|KEYWORD|LOCATION\([^)]+\)):(.+)\}", s)
    if m:
        return len(m.group(1)) <= max_len
    return len(s) <= max_len


def validate_rsa(headlines: list[str], descs: list[str], where: str) -> None:
    assert len(headlines) == 15, f"{where}: need 15 headlines, got {len(headlines)}"
    assert len(descs) == 4, f"{where}: need 4 descriptions, got {len(descs)}"
    assert all(h.strip() for h in headlines), f"{where}: blank headline"
    assert all(d.strip() for d in descs), f"{where}: blank description"
    assert len(set(headlines)) == 15, f"{where}: duplicate headlines"
    assert len(set(descs)) == 4, f"{where}: duplicate descriptions"
    for i, h in enumerate(headlines, 1):
        if not _len_ok(h, HL_MAX):
            raise ValueError(f"{where} H{i} too long ({len(h)}): {h!r}")
    for i, d in enumerate(descs, 1):
        if len(d) > DESC_MAX:
            raise ValueError(f"{where} D{i} too long ({len(d)}): {d!r}")
    for p in ():
        pass


# Spend from ads-launch/_rsa_challenger_review.json launch window (4–13 Aug).
# Zero good Zoho employers on these groups. Skip frozen winners + Brand.
GROUPS: list[dict] = [
    # ——— US provider-intent (hub /us) ———
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "Offshore_VA_PH",
        "ad_group_id": "198704755363",
        "model": "provider",
        "cost": 95.08,
        "clicks": 45,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us",
        "path1": "offshore",
        "path2": "staff",
        "headlines": [
            "Offshore Staffing Partner",
            "Dedicated Filipino Employee",
            "We Recruit and Vet",
            "You Interview. You Pick.",
            "Employment Admin Handled",
            "Not a Freelance Bench",
            "Philippines Staff. US Hours.",
            "Book a Hiring Consultation",
            "Staffing Partner Since 2011",
            "One Seat. Your Company.",
            "Offices. Reviews. History.",
            "Skip the Gig Marketplace",
            "You Keep Hire Control",
            "Dedicated. Not Rotating.",
            "US Employers Hiring Staff",
        ],
        "descriptions": [
            "Offshore staffing partner for US employers. Dedicated Filipino employee, not freelance.",
            "We recruit and vet. You interview. We handle employment admin after you say yes.",
            "Philippines staff on your US hours. Book a hiring consultation. Employers only.",
            "Not a marketplace or job board. One dedicated seat, screened for your role, on your hours.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "Agency_PH",
        "ad_group_id": "201789221009",
        "model": "provider",
        "cost": 87.55,
        "clicks": 34,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us",
        "path1": "agency",
        "path2": "partner",
        "headlines": [
            "Virtual Assistant Agency",
            "Established Staffing Partner",
            "Dedicated Filipino Employee",
            "We Recruit and Vet",
            "You Interview the Shortlist",
            "Employment Admin Handled",
            "Not a Freelance Agency",
            "Book a Hiring Consultation",
            "Staffing Firm Since 2011",
            "US Hours. One Dedicated Seat.",
            "Reviews, Offices, History",
            "Skip Marketplace Guesswork",
            "You Choose Who Joins",
            "Agency. Not a Job Board.",
            "Employers Hiring a Partner",
        ],
        "descriptions": [
            "A virtual assistant agency and staffing partner — dedicated Filipino employee, not gigs.",
            "We recruit and vet. You interview. Employment admin handled. Nobody starts until you pick.",
            "Looking for an agency, not a marketplace? Book a hiring consultation. Employers only.",
            "US offices and a Philippines hub. Reviews and history you can check. One seat. Your hours.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "Staffing_Agency_PH",
        "ad_group_id": "199533991056",
        "model": "provider",
        "cost": 74.05,
        "clicks": 27,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us",
        "path1": "staffing",
        "path2": "partner",
        "headlines": [
            "Remote Staffing Partner",
            "Dedicated Filipino Employee",
            "We Recruit and Vet",
            "You Interview. You Decide.",
            "Employment Admin Handled",
            "Not a Temp Marketplace",
            "Book a Hiring Consultation",
            "Staffing Partner Since 2011",
            "US Hours. Philippines Staff.",
            "Offices You Can Verify",
            "Skip Freelance Staffing",
            "One Person. Your Workflow.",
            "Reviews and Real History",
            "Employers Hiring Remote Staff",
            "You Keep the Hire Decision",
        ],
        "descriptions": [
            "Remote staffing partner for US teams. Dedicated Filipino employee — not temps or gigs.",
            "We recruit and vet. You interview the shortlist. We handle employment admin and stay on.",
            "Not Upwork and not a temp agency. One dedicated seat on your hours, matched to the role.",
            "Book a hiring consultation. Employers only. Offices, reviews, and history since 2011.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "VA_Agency_Firm_PH",
        "ad_group_id": "199533991096",
        "model": "provider",
        "cost": 1.98,
        "clicks": 1,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us",
        "path1": "firm",
        "path2": "hire",
        "headlines": [
            "Virtual Assistant Firm",
            "Staffing Partner, Not Gigs",
            "Dedicated Filipino Employee",
            "We Recruit and Vet",
            "You Interview Finalists",
            "Employment Admin Handled",
            "Book a Hiring Consultation",
            "Firm. Not a Marketplace.",
            "Staffing Since 2011",
            "US Employers. Not Seekers.",
            "One Seat. Your Company.",
            "Offices and Real Reviews",
            "Skip Freelance VA Apps",
            "You Choose Who Joins",
            "Philippines Staff. US Hours.",
        ],
        "descriptions": [
            "A virtual assistant firm for US employers — dedicated Filipino employee, not a gig app.",
            "We recruit and vet. You interview. Employment admin handled. Nobody starts until you pick.",
            "Agency and firm searches stay on the hub. Book a hiring consultation. Employers only.",
            "Serving businesses since 2011. Offices, reviews, history — not a freelance board.",
        ],
    },
    # ——— US role-hiring ———
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Bookkeeping_Hire_PH",
        "ad_group_id": "198704756443",
        "model": "role",
        "cost": 60.45,
        "clicks": 18,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us/bookkeeping",
        "path1": "books",
        "path2": "hire",
        "headlines": [
            "Hire a Bookkeeper",
            "Invoices Stacking Up?",
            "Dedicated Bookkeeper Seat",
            "Filipino Bookkeeper Hire",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Books Falling Behind?",
            "Book a Hiring Consultation",
            "Not a Freelance Bookkeeper",
            "Reconcile Without the Pile",
            "Dedicated Books Teammate",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Teams Hiring Books Help",
        ],
        "descriptions": [
            "Invoices stacking up? Hire a dedicated Filipino bookkeeper on your US hours — not a gig.",
            "We recruit and vet. You interview. Reconciliations and routine reporting leave your desk.",
            "Book a hiring consultation. The form already has bookkeeping selected. Employers only.",
            "One dedicated books teammate. You pick who joins. We handle employment admin after yes.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Recruitment_Hire_PH",
        "ad_group_id": "198704756563",
        "model": "role",
        "cost": 50.52,
        "clicks": 13,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us/recruitment",
        "path1": "recruit",
        "path2": "hire",
        "headlines": [
            "Hire Recruiting Support",
            "Hiring Slowing You Down?",
            "Dedicated Recruiting Seat",
            "Filipino Recruiting Hire",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Screens Without the Chase",
            "Book a Hiring Consultation",
            "Not Freelance Recruiters",
            "Sourcing Help You Keep",
            "Interview Scheduling Help",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US TA Teams Hiring Help",
        ],
        "descriptions": [
            "Hiring slowing you down? Hire dedicated Filipino recruiting support.",
            "We recruit and vet. You interview. One recruiting teammate on your US hours.",
            "Book a hiring consultation. This page is for a recruitment seat — not a generic VA search.",
            "You pick who joins. We handle employment admin. Employers hiring recruiting help only.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Digital_Marketing_Hire_PH",
        "ad_group_id": "198704755403",
        "model": "role",
        "cost": 44.74,
        "clicks": 14,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us/digital-marketing",
        "path1": "marketing",
        "path2": "hire",
        "headlines": [
            "Hire a Marketer",
            "Campaigns Stalling Out?",
            "Dedicated Marketing Seat",
            "Filipino Marketer Hire",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Reporting Still On You?",
            "Book a Hiring Consultation",
            "Not a Freelance Marketer",
            "Campaigns Need an Owner",
            "Content Ops That Move",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Brands Hiring Marketing",
        ],
        "descriptions": [
            "Campaigns stalling? Hire a dedicated Filipino marketer on your US hours — not a freelance.",
            "We recruit and vet. You interview. Campaigns, reporting, and content ops get an owner.",
            "Book a hiring consultation. Digital marketing is already selected in the form.",
            "One dedicated marketing teammate. You pick who joins. We handle employment admin.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Appointment_Setter_Hire_PH",
        "ad_group_id": "199533991216",
        "model": "role",
        "cost": 21.58,
        "clicks": 7,
        "enabled_effective": 2,
        "final_url": "https://www.virtualcoworker.app/us/sales",
        "path1": "sales",
        "path2": "setter",
        "headlines": [
            "Hire an Appointment Setter",
            "Calendar Staying Empty?",
            "Dedicated Setter Seat",
            "Filipino Appointment Setter",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Outreach Without the Chase",
            "Book a Hiring Consultation",
            "Not a Freelance Setter",
            "Lists and Follow-Ups Owned",
            "Sales Support You Keep",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Sales Teams Hiring",
        ],
        "descriptions": [
            "Calendar staying empty? Hire a dedicated Filipino appointment setter on your US hours.",
            "We recruit and vet. You interview. Lists, outreach support, and follow-ups get an owner.",
            "Book a hiring consultation. Lands on the sales page with the role ready in the form.",
            "Not a freelance setter. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Social_Media_Outsource_PH",
        "ad_group_id": "198704756643",
        "model": "role",
        "cost": 18.29,
        "clicks": 5,
        "enabled_effective": 1,
        "final_url": "https://www.virtualcoworker.app/us/social-media",
        "path1": "social",
        "path2": "seat",
        "headlines": [
            "Hire Social Media Staff",
            "Channels Going Quiet?",
            "Dedicated Social Seat",
            "Filipino Social Teammate",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Scheduling and Community",
            "Book a Hiring Consultation",
            "Not a Freelance Poster",
            "Channels Stay Active",
            "One Owner. Your Brand.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Brands Hiring Social",
        ],
        "descriptions": [
            "Channels going quiet? Hire a dedicated Filipino social teammate on your US hours.",
            "We recruit and vet. You interview. Scheduling, replies, and assets get one owner.",
            "Book a hiring consultation. Role page — not a generic VA dump. Employers only.",
            "Not a freelance poster. One dedicated social seat. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Customer_Service_Outsource_PH",
        "ad_group_id": "198704756483",
        "model": "role",
        "cost": 16.88,
        "clicks": 5,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us/customer-service",
        "path1": "support",
        "path2": "outsource",
        "headlines": [
            "Hire Customer Support Staff",
            "Tickets Piling Up?",
            "Dedicated Support Seat",
            "Filipino Support Hire",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Chat and Follow-Through",
            "Book a Hiring Consultation",
            "Not Freelance Support",
            "Customers Wait Less",
            "One Owner. Your Queue.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Teams Hiring Support",
        ],
        "descriptions": [
            "Tickets piling up? Hire dedicated Filipino customer support staff on your US hours.",
            "We recruit and vet. You interview. Tickets, chat, and follow-through get an owner.",
            "Book a hiring consultation. Customer service is already selected in the form.",
            "Not freelance support. One dedicated seat. You pick who joins. We handle employment admin.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Administration_EA_PH",
        "ad_group_id": "198704755443",
        "model": "role",
        "cost": 13.16,
        "clicks": 4,
        "enabled_effective": 2,
        "final_url": "https://www.virtualcoworker.app/us/administrative-support",
        "path1": "admin",
        "path2": "hire",
        "headlines": [
            "Hire a Virtual Assistant",
            "Inbox Eating Your Week?",
            "Dedicated Admin Teammate",
            "Filipino Executive Assistant",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Calendar and Follow-Ups",
            "Book a Hiring Consultation",
            "Not a Freelance Assistant",
            "Inbox Stops Owning You",
            "One Admin Seat. Yours.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Teams Hiring Admin",
        ],
        "descriptions": [
            "Inbox eating your week? Hire a dedicated Filipino virtual assistant on your US hours.",
            "We recruit and vet. You interview. Inbox, calendar, and follow-ups get one owner.",
            "Book a hiring consultation. Admin role is preselected on this page. Employers only.",
            "Not a freelance assistant. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Customer_Service_Hire_PH",
        "ad_group_id": "198704756403",
        "model": "role",
        "cost": 12.29,
        "clicks": 4,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us/customer-service",
        "path1": "support",
        "path2": "hire",
        "headlines": [
            "Hire Customer Support",
            "Queue Never Clearing?",
            "Dedicated Support Hire",
            "Filipino Support Staff",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Tickets Need an Owner",
            "Book a Hiring Consultation",
            "Not a Support Marketplace",
            "Chat That Gets Closed",
            "One Seat. Your Customers.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Support Teams Hiring",
        ],
        "descriptions": [
            "Queue never clearing? Hire dedicated Filipino customer support on your US hours.",
            "We recruit and vet. You interview. Tickets and chat stop bouncing back to you.",
            "Book a hiring consultation. Customer service is already selected in the form.",
            "Not a support marketplace. One dedicated teammate. You pick. Employment admin handled.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Admin_City_Test",
        "ad_group_id": "199533991176",
        "model": "role",
        "cost": 12.03,
        "clicks": 4,
        "enabled_effective": 1,
        "final_url": "https://www.virtualcoworker.app/us/administrative-support",
        "path1": "admin",
        "path2": "local",
        "headlines": [
            "Hire Admin Support",
            "Still Doing the Admin?",
            "Dedicated Admin Seat",
            "Filipino Admin Hire",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Docs and Coordination",
            "Book a Hiring Consultation",
            "Not a Freelance Admin",
            "Managers Get Time Back",
            "One Admin. Your Hours.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Offices Hiring Admin",
        ],
        "descriptions": [
            "Still doing the admin yourself? Hire a dedicated Filipino admin teammate on your US hours.",
            "We recruit and vet. You interview. Docs, coordination, and follow-ups leave your week.",
            "Book a hiring consultation. Same admin page as the main admin group. Employers only.",
            "City-test group stays on the admin role page. No generic hub dump. You pick who joins.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Sales_Hire_PH",
        "ad_group_id": "198704756603",
        "model": "role",
        "cost": 6.81,
        "clicks": 3,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us/sales",
        "path1": "sales",
        "path2": "hire",
        "headlines": [
            "Hire Sales Support Staff",
            "CRM Getting Messy?",
            "Dedicated Sales Seat",
            "Filipino Sales Support",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Lists and Outreach Help",
            "Book a Hiring Consultation",
            "Not Freelance Sales Help",
            "Pipeline Hygiene Owned",
            "One Seat. Your CRM.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Sales Teams Hiring",
        ],
        "descriptions": [
            "CRM getting messy? Hire dedicated Filipino sales support staff on your US hours.",
            "We recruit and vet. You interview. Lists, outreach support, and CRM hygiene get an owner.",
            "Book a hiring consultation. Sales is preselected. Employers hiring support — not reps.",
            "Not freelance sales help. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Digital_Marketing_Outsource_PH",
        "ad_group_id": "198704755483",
        "model": "role",
        "cost": 6.32,
        "clicks": 2,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/us/digital-marketing",
        "path1": "marketing",
        "path2": "outsource",
        "headlines": [
            "Outsource Marketing Staff",
            "Execution Still Slipping?",
            "Dedicated Marketing Hire",
            "Filipino Marketing Seat",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Day-to-Day Campaign Ops",
            "Book a Hiring Consultation",
            "Not Freelance Campaigns",
            "Strategists Keep Judgment",
            "One Owner. Your Tools.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Marketing Teams Hiring",
        ],
        "descriptions": [
            "Execution still slipping? Outsource to a dedicated Filipino marketer — not freelancers.",
            "We recruit and vet. You interview. Day-to-day campaign ops get an owner on your US hours.",
            "Book a hiring consultation. Same marketing page. Role is preselected. Employers only.",
            "Not freelance campaigns. One dedicated seat. You pick who joins. Employment admin handled.",
        ],
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Social_Media_Hire_PH",
        "ad_group_id": "198704756523",
        "model": "role",
        "cost": 2.43,
        "clicks": 1,
        "enabled_effective": 2,
        "final_url": "https://www.virtualcoworker.app/us/social-media",
        "path1": "social",
        "path2": "hire",
        "headlines": [
            "Hire a Social Media Manager",
            "Brand Going Quiet?",
            "Dedicated Social Hire",
            "Filipino Social Manager",
            "On Your US Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Posting and Replies Owned",
            "Book a Hiring Consultation",
            "Not a Freelance Poster",
            "Channels Need an Owner",
            "One Teammate. Your Voice.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "US Brands Hiring Social",
        ],
        "descriptions": [
            "Brand going quiet? Hire a dedicated Filipino social media manager on your US hours.",
            "We recruit and vet. You interview. Posting, community, and assets get one owner.",
            "Book a hiring consultation. US social page — not the frozen AU path. Employers only.",
            "Not a freelance poster. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    # ——— AU provider-intent (hub /au) ———
    {
        "market": "AU",
        "campaign": "VC_AU_S_CORE",
        "ad_group": "Hire_VA_PH",
        "ad_group_id": "199115614277",
        "model": "provider",
        "cost": 266.43,
        "clicks": 75,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/au",
        "path1": "staff",
        "path2": "partner",
        "headlines": [
            "Staffing Partner Australia",
            "Dedicated Filipino Employee",
            "We Recruit and Vet",
            "You Interview. You Pick.",
            "Employment Admin Handled",
            "Not a Freelance Board",
            "Australian Hours. One Seat.",
            "Book a Hiring Consultation",
            "Staffing Partner Since 2011",
            "Offices. Reviews. History.",
            "Agency and Provider Search",
            "Skip Marketplace Hiring",
            "You Keep Hire Control",
            "Dedicated. Not Rotating.",
            "Australian Employers Hiring",
        ],
        "descriptions": [
            "Staffing partner for Australian employers. Dedicated Filipino employee, not freelance.",
            "We recruit and vet. You interview. We handle employment admin after you say yes.",
            "Australian hours. Book a hiring consultation. Employers only. Offices, reviews, history.",
            "Provider and agency searches stay on the AU hub. Not a role page. Not a job board.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_CORE",
        "ad_group": "Agency_PH",
        "ad_group_id": "201790140569",
        "model": "provider",
        "cost": 56.55,
        "clicks": 14,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/au",
        "path1": "agency",
        "path2": "hire",
        "headlines": [
            "Virtual Assistant Agency",
            "Established Staffing Partner",
            "Dedicated Filipino Employee",
            "We Recruit and Vet",
            "You Interview the Shortlist",
            "Employment Admin Handled",
            "Not a Freelance Agency",
            "Book a Hiring Consultation",
            "Staffing Firm Since 2011",
            "Australian Hours. One Seat.",
            "Reviews, Offices, History",
            "Skip Marketplace Guesswork",
            "You Choose Who Joins",
            "Agency. Not a Job Board.",
            "Australian Employers Hiring",
        ],
        "descriptions": [
            "A virtual assistant agency and staffing partner — dedicated Filipino employee, not gigs.",
            "We recruit and vet. You interview. Employment admin handled. Nobody starts until you pick.",
            "Looking for an agency in Australia? Book a hiring consultation. Employers only.",
            "Stays on the AU hub. Not a role page. Offices, reviews, and history you can check.",
        ],
    },
    # ——— AU role-hiring ———
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Recruitment_Hire_PH",
        "ad_group_id": "199115615677",
        "model": "role",
        "cost": 83.53,
        "clicks": 22,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/au/recruitment",
        "path1": "recruit",
        "path2": "hire",
        "headlines": [
            "Hire Recruiting Support",
            "Hiring Still Slowing You?",
            "Dedicated Recruiting Seat",
            "Filipino Recruiting Hire",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Screens Without the Chase",
            "Book a Hiring Consultation",
            "Not Freelance Recruiters",
            "Sourcing Help You Keep",
            "Interview Scheduling Help",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian TA Teams Hiring",
        ],
        "descriptions": [
            "Hiring still slowing you? Hire dedicated Filipino recruiting support on Australian hours.",
            "We recruit and vet. You interview. This is the recruiting seat — not a generic VA dump.",
            "Book a hiring consultation. File 02 already pauses the junk generic keyword.",
            "Not freelance recruiters. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Administration_EA_PH",
        "ad_group_id": "199115614357",
        "model": "role",
        "cost": 26.11,
        "clicks": 6,
        "enabled_effective": 2,
        "final_url": "https://www.virtualcoworker.app/au/administrative-support",
        "path1": "admin",
        "path2": "hire",
        "headlines": [
            "Hire a Virtual Assistant",
            "Still Doing the Admin?",
            "Dedicated Admin Teammate",
            "Filipino Virtual Assistant",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Inbox and Follow-Ups",
            "Book a Hiring Consultation",
            "Not a Freelance Assistant",
            "Managers Get Time Back",
            "One Admin Seat. Yours.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Teams Hiring",
        ],
        "descriptions": [
            "Still doing the admin yourself? Hire a dedicated Filipino VA on Australian hours.",
            "We recruit and vet. You interview. Inbox, calendar, and follow-ups get one owner.",
            "Book a hiring consultation. Admin is preselected on this page. Employers only.",
            "Not a freelance assistant. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Customer_Service_Hire_PH",
        "ad_group_id": "199115614837",
        "model": "role",
        "cost": 14.49,
        "clicks": 3,
        "enabled_effective": 2,
        "final_url": "https://www.virtualcoworker.app/au/customer-service",
        "path1": "support",
        "path2": "hire",
        "headlines": [
            "Hire Customer Support Staff",
            "Queue Never Clearing?",
            "Dedicated Support Seat",
            "Filipino Support Hire",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Tickets Need an Owner",
            "Book a Hiring Consultation",
            "Not Freelance Support",
            "Chat That Gets Closed",
            "One Seat. Your Customers.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Teams Hiring",
        ],
        "descriptions": [
            "Queue never clearing? Hire dedicated Filipino customer support staff on Australian hours.",
            "We recruit and vet. You interview. Tickets and chat stop bouncing back to you.",
            "Book a hiring consultation. Customer service is already selected in the form.",
            "Not freelance support. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Bookkeeping_Hire_PH",
        "ad_group_id": "199115614597",
        "model": "role",
        "cost": 13.15,
        "clicks": 4,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/au/bookkeeping",
        "path1": "books",
        "path2": "hire",
        "headlines": [
            "Hire a Bookkeeper",
            "Books Falling Behind?",
            "Dedicated Bookkeeper Seat",
            "Filipino Bookkeeper Hire",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Invoices Still On Your Desk?",
            "Book a Hiring Consultation",
            "Not a Freelance Bookkeeper",
            "Reconcile Without the Pile",
            "Dedicated Books Teammate",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Teams Hiring",
        ],
        "descriptions": [
            "Books falling behind? Hire a dedicated Filipino bookkeeper on Australian hours.",
            "We recruit and vet. You interview. Invoices and routine reporting leave your desk.",
            "Book a hiring consultation. Bookkeeping is already selected in the form. Employers only.",
            "One dedicated books teammate. You pick who joins. We handle employment admin after yes.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Customer_Service_Outsource_PH",
        "ad_group_id": "199115614877",
        "model": "role",
        "cost": 12.07,
        "clicks": 4,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/au/customer-service",
        "path1": "support",
        "path2": "outsource",
        "headlines": [
            "Outsource Support Staff",
            "Tickets Still Piling Up?",
            "Dedicated Support Hire",
            "Filipino Support Staff",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Chat and Follow-Through",
            "Book a Hiring Consultation",
            "Not a Support Marketplace",
            "Customers Wait Less",
            "One Owner. Your Queue.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Support Hiring",
        ],
        "descriptions": [
            "Tickets still piling up? Outsource to dedicated Filipino support on Australian hours.",
            "We recruit and vet. You interview. Tickets, chat, and follow-through get an owner.",
            "Book a hiring consultation. Same support page. Role is preselected. Employers only.",
            "Not a support marketplace. One dedicated seat. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Accounting_Hire_PH",
        "ad_group_id": "199115614517",
        "model": "role",
        "cost": 8.92,
        "clicks": 3,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/au/accounting",
        "path1": "accounting",
        "path2": "hire",
        "headlines": [
            "Hire Accounting Support",
            "Month-End Still a Scramble?",
            "Dedicated Accounting Seat",
            "Filipino Accounting Hire",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Recurring Work Stacking?",
            "Book a Hiring Consultation",
            "Not Licensed Advice",
            "Extra Capacity. Your Tools.",
            "AP and AR Support Staff",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Finance Hiring",
        ],
        "descriptions": [
            "Month-end still a scramble? Hire dedicated Filipino accounting support. Australian hours.",
            "We recruit and vet. You interview. Extra capacity — not a substitute for your accountant.",
            "Book a hiring consultation. Accounting is already selected in the form. Employers only.",
            "Not freelance book tasks. One dedicated seat. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Social_Media_Outsource_PH",
        "ad_group_id": "199115614757",
        "model": "role",
        "cost": 5.92,
        "clicks": 1,
        "enabled_effective": 1,
        "final_url": "https://www.virtualcoworker.app/au/social-media",
        "path1": "social",
        "path2": "outsource",
        "headlines": [
            "Outsource Social Staff",
            "Social Still Going Quiet?",
            "Dedicated Social Seat",
            "Filipino Social Teammate",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Scheduling and Community",
            "Book a Hiring Consultation",
            "Not a Freelance Poster",
            "Channels Stay Active",
            "One Owner. Your Brand.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Brands Hiring",
        ],
        "descriptions": [
            "Social still going quiet? Outsource to a dedicated Filipino social teammate. AU hours.",
            "We recruit and vet. You interview. Scheduling, replies, and assets get one owner.",
            "Same /au/social-media page as the frozen hire group. This ad stays Paused.",
            "Not a freelance poster. One dedicated seat. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Sales_Hire_PH",
        "ad_group_id": "199115615797",
        "model": "role",
        "cost": 5.46,
        "clicks": 2,
        "enabled_effective": 2,
        "final_url": "https://www.virtualcoworker.app/au/sales",
        "path1": "sales",
        "path2": "hire",
        "headlines": [
            "Hire Sales Support Staff",
            "CRM Getting Messy?",
            "Dedicated Sales Seat",
            "Filipino Sales Support",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Lists and Outreach Help",
            "Book a Hiring Consultation",
            "Not Freelance Sales Help",
            "Pipeline Hygiene Owned",
            "One Seat. Your CRM.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Sales Hiring",
        ],
        "descriptions": [
            "CRM getting messy? Hire dedicated Filipino sales support staff on Australian hours.",
            "We recruit and vet. You interview. Lists, outreach support, and CRM hygiene get an owner.",
            "Book a hiring consultation. Sales is preselected. Employers hiring support — not reps.",
            "Not freelance sales help. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Recruitment_Outsource_PH",
        "ad_group_id": "199115615717",
        "model": "role",
        "cost": 2.17,
        "clicks": 1,
        "enabled_effective": 1,
        "final_url": "https://www.virtualcoworker.app/au/recruitment",
        "path1": "recruit",
        "path2": "outsource",
        "headlines": [
            "Outsource Recruiting Help",
            "Sourcing Still On You?",
            "Dedicated Recruiting Hire",
            "Filipino Recruiting Seat",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Screens and Scheduling",
            "Book a Hiring Consultation",
            "Not Freelance Recruiters",
            "TA Ops You Can Keep",
            "One Seat. Your Pipeline.",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian TA Hiring",
        ],
        "descriptions": [
            "Sourcing still on you? Outsource dedicated Filipino recruiting support. Australian hours.",
            "We recruit and vet. You interview. Stays on the recruitment page — not a generic VA dump.",
            "Book a hiring consultation. Role is preselected. Employers only. Not a job-seeker page.",
            "Not freelance recruiters. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Digital_Marketing_Hire_PH",
        "ad_group_id": "199115614397",
        "model": "role",
        "cost": 1.71,
        "clicks": 1,
        "enabled_effective": 3,
        "final_url": "https://www.virtualcoworker.app/au/digital-marketing",
        "path1": "marketing",
        "path2": "hire",
        "headlines": [
            "Hire a Marketer",
            "Marketing Still Slipping?",
            "Dedicated Marketing Seat",
            "Filipino Marketer Hire",
            "On Australian Hours",
            "We Recruit and Vet",
            "You Interview First",
            "Campaigns Need an Owner",
            "Book a Hiring Consultation",
            "Not a Freelance Marketer",
            "Reporting Leaves Your Desk",
            "Content Ops That Move",
            "You Choose Who Joins",
            "Employment Admin Handled",
            "Australian Brands Hiring",
        ],
        "descriptions": [
            "Marketing still slipping? Hire a dedicated Filipino marketer on Australian hours.",
            "We recruit and vet. You interview. Campaigns, reporting, and content ops get an owner.",
            "Book a hiring consultation. Digital marketing is already selected in the form.",
            "Not a freelance marketer. One dedicated teammate. You pick. We handle employment admin.",
        ],
    },
]


SKIPPED = [
    {
        "ad_group": "Hire_VA_PH",
        "market": "US",
        "why": "Frozen winner. Exact+Phrase virtual assistant agency in usa Enabled. Do not add or edit RSAs.",
    },
    {
        "ad_group": "Social_Media_Hire_PH",
        "market": "AU",
        "why": "Frozen winner. Phrase hire a social media manager. Do not edit enabled RSAs.",
    },
    {
        "ad_group": "Brand_VC",
        "market": "US+AU",
        "why": "Brand deferred. No challenger.",
    },
]


def comment_for(g: dict) -> str:
    cap = (
        "3-ad cap: paused extra — do not Enable a 4th"
        if g["enabled_effective"] >= 3
        else f"{g['enabled_effective']} enabled now — keep this Paused until George Enables"
    )
    return (
        f"{LABEL} · after file 02 · {g['model']} · Paused · {cap} · "
        f"Final URL stays {g['final_url']} · do not mix with 02"
    )


def ad_row(g: dict) -> dict:
    validate_rsa(g["headlines"], g["descriptions"], f"{g['market']}/{g['ad_group']}")
    for key in ("path1", "path2"):
        if len(g[key]) > PATH_MAX:
            raise ValueError(f"{g['ad_group']} {key} too long: {g[key]!r}")
    row = {k: "" for k in HEADER}
    row["Account"] = ACCOUNT[g["market"]]
    row["Row Type"] = "Ad"
    row["Campaign"] = g["campaign"]
    row["Campaign Type"] = "Search"
    row["Networks"] = "Google Search"
    row["Languages"] = "en"
    row["Location options"] = "Presence"
    row["Ad Group"] = g["ad_group"]
    row["Ad Status"] = "Paused"
    row["Ad type"] = "Responsive search ad"
    row["Final URL"] = g["final_url"]
    row["Path 1"] = g["path1"]
    row["Path 2"] = g["path2"]
    for i, h in enumerate(g["headlines"], 1):
        row[f"Headline {i}"] = h
    for i, d in enumerate(g["descriptions"], 1):
        row[f"Description {i}"] = d
    row["Labels"] = LABEL
    row["Comment"] = comment_for(g)
    return row


def write_csv(path: Path, groups: list[dict]) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADER, lineterminator="\n")
        w.writeheader()
        for g in groups:
            w.writerow(ad_row(g))


def main() -> int:
    for g in GROUPS:
        validate_rsa(g["headlines"], g["descriptions"], f"{g['market']}/{g['ad_group']}")
    us = [g for g in GROUPS if g["market"] == "US"]
    au = [g for g in GROUPS if g["market"] == "AU"]
    write_csv(OUT_US, us)
    write_csv(OUT_AU, au)
    payload = {
        "title": "Spend-only paused RSA challengers",
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "import_after": "ads-launch/aug18-winners/02-au-recruitment-junk-reversible.csv",
        "do_not_mix_with_02": True,
        "all_ad_status": "Paused",
        "protect_label_applied": False,
        "ads_oauth": "invalid_grant — no live Ads confirm",
        "spend_source": "ads-launch/_rsa_challenger_review.json launch window 4–13 Aug 2026",
        "skipped": SKIPPED,
        "groups": [
            {
                "market": g["market"],
                "campaign": g["campaign"],
                "ad_group": g["ad_group"],
                "ad_group_id": g["ad_group_id"],
                "model": g["model"],
                "cost_launch": g["cost"],
                "clicks_launch": g["clicks"],
                "enabled_effective": g["enabled_effective"],
                "three_ad_cap": g["enabled_effective"] >= 3,
                "action": "paused_extra"
                if g["enabled_effective"] >= 3
                else "paused_new",
                "final_url": g["final_url"],
                "path1": g["path1"],
                "path2": g["path2"],
                "headlines": g["headlines"],
                "descriptions": g["descriptions"],
                "serp_title": " · ".join(g["headlines"][:3]),
                "serp_desc": g["descriptions"][0],
            }
            for g in GROUPS
        ],
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    XRAY_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_US.name} ({len(us)} ads)")
    print(f"Wrote {OUT_AU.name} ({len(au)} ads)")
    print(f"Wrote {OUT_JSON.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
