#!/usr/bin/env python3
"""Write MyOutDesk research CSVs/JSON from confirmed extracts + probe CSV."""

from __future__ import annotations

import csv
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

OUT = Path("/Users/george/Developer/virtual-coworker/ads-launch/research/myoutdesk-2026-08-18")


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def write_lp_csv() -> None:
    rows = [
        {
            "full_url": "https://www.myoutdesk.com/lp/google-philippines-virtual-assistants/",
            "clean_url": "https://www.myoutdesk.com/lp/google-philippines-virtual-assistants/",
            "slug": "google-philippines-virtual-assistants",
            "page_title": "Philippines Virtual Assistants | MyOutDesk",
            "meta_description": "Hire a dedicated, college-educated virtual assistant from the Philippines. Fluent English, US business hours, and up to 70% lower cost than a local hire.",
            "canonical_url": "https://www.myoutdesk.com/lp/google-philippines-virtual-assistants/",
            "index_status": "noindex, nofollow, noarchive",
            "h1": "Hire a Virtual Assistant From the Philippines. Buy back your time, cut overhead up to 70%, and scale without hiring drag.",
            "h2s": "Find Your Virtual Assistant Today | The world's #1 destination for virtual assistants | Make MyOutDesk your strategic partner in the Philippines | How we compare | How it works | Built for trust",
            "hero_copy_paraphrase": "PH-origin dedicated VA; time back; up to 70% overhead cut; scale without local hiring drag",
            "cta": "Find your virtual assistant / Book a strategy session (#book-call / #signup)",
            "phone_prominence": "No tel: CTA in ATF; public site phone is (800) 583-9950 on homepage JSON-LD, not this LP",
            "form_structure": "fullName, businessEmail, companyName, phoneNumber, terms checkbox; hidden utm_campaign/medium/source/term/content/placement/platform, gclid, fbclid, msclkid, gbraid, wbraid, ga_cid/mid, fbc/fbp, first_landing_url",
            "primary_role": "general VA (role grid: admin, CS, SDR, bookkeeping, marketing, recruiting, TC, CRM, receptionist, PM coordinator, EA, lead gen)",
            "industry": "cross-industry",
            "geography": "Philippines talent; US business hours / Western alignment",
            "employer_intent_theme": "hire dedicated PH VA; outsourcing partner; not a job application",
            "proof_elements": "18+ years; 8,500+ clients; $140M saved claim; 4.9 Google; 0.7% pass rate; college-educated; SOC 2; HIPAA; rematch; US hours",
            "offer_and_conversion": "Free strategy call / find-VA form; savings-report theme on sibling pages",
            "internal_links": "Self-canonical only in HTML (noindex/nofollow); conversion is on-page anchors",
            "tracking_patterns": "utm_* + gclid family hidden fields; GTM-N589823; GrowthBook; Conversion.ai; ChiliPiper; LinkedIn 7070116; Clarity e4i40pe530; CookieYes",
            "probable_target_keyword": "virtual assistant in the philippines",
            "related_keyword_variations": "philippines virtual assistants; hire virtual assistant philippines; filipino virtual assistant",
            "probable_campaign": "LM_US_Virtual_Assistants_Outsourcing",
            "probable_ad_group": "Virtual_Assistants_Outsourcing",
            "gad_campaignid_observed": "23338767511 (from original click; not re-requested)",
            "utm_term_observed": "virtual assistant in the philippines_e",
            "match_type_inference": "exact (_e suffix)",
            "page_type": "paid_geo_lp",
            "in_sitemap": "no",
            "evidence_source": "seed click params + clean GET cache 2026-08-18",
            "confidence": "observed (page) / high-confidence inference (campaign/keyword)",
        },
        {
            "full_url": "https://www.myoutdesk.com/lp/google-virtual-assistants/",
            "clean_url": "https://www.myoutdesk.com/lp/google-virtual-assistants/",
            "slug": "google-virtual-assistants",
            "page_title": "Virtual Assistants | MyOutDesk",
            "meta_description": "Boost productivity and cut overhead costs by up to 70% with experienced virtual assistants who provide top-tier support.",
            "canonical_url": "https://www.myoutdesk.com/lp/google-virtual-assistants/",
            "index_status": "noindex, nofollow, noarchive",
            "h1": "Award Winning Virtual Assistant Services. Buy back your time, cut overhead up to 70%, and scale without hiring drag.",
            "h2s": "Find Your Virtual Assistant Today | Make MyOutDesk your strategic partner for outsourcing | How we compare | How it works",
            "hero_copy_paraphrase": "Generic award-winning VA services; same time/overhead/scale frame as PH LP without country in H1",
            "cta": "Find your virtual assistant",
            "phone_prominence": "Not the primary CTA",
            "form_structure": "Same employer form + hidden click IDs as other /lp/google-* pages",
            "primary_role": "general VA (same role grid as PH LP)",
            "industry": "cross-industry",
            "geography": "unspecified on H1; PH implied by company model",
            "employer_intent_theme": "generic hire-a-VA / outsourcing partner",
            "proof_elements": "8,500+; $140M; 18 years; 70%; SOC 2; HIPAA; 0.7%; college; 4.9; rematch",
            "offer_and_conversion": "On-page find-VA / strategy form",
            "internal_links": "Self-canonical; on-page conversion anchors",
            "tracking_patterns": "Same GTM-N589823 + UTM/gclid hidden fields",
            "probable_target_keyword": "virtual assistants",
            "related_keyword_variations": "virtual assistant; hire virtual assistant; virtual assistant services",
            "probable_campaign": "LM_US_Virtual_Assistants_* or generic non-geo Search (not on seed click)",
            "probable_ad_group": "Virtual_Assistants or Virtual_Assistants_Outsourcing",
            "gad_campaignid_observed": "",
            "utm_term_observed": "",
            "match_type_inference": "speculative; slug is plural head term",
            "page_type": "paid_generic_head_term_lp",
            "in_sitemap": "no",
            "evidence_source": "clean GET 2026-08-18; unique body hash vs PH LP",
            "confidence": "observed (page) / speculative (campaign name)",
        },
        {
            "full_url": "https://www.myoutdesk.com/lp/google-real-estate-virtual-assistants/",
            "clean_url": "https://www.myoutdesk.com/lp/google-real-estate-virtual-assistants/",
            "slug": "google-real-estate-virtual-assistants",
            "page_title": "Real Estate Virtual Assistants | MyOutDesk",
            "meta_description": "Rapidly grow your real estate business and generate massive revenue while cutting costs with a Real Estate Virtual Assistant.",
            "canonical_url": "https://www.myoutdesk.com/lp/google-real-estate-virtual-assistants/",
            "index_status": "noindex, nofollow, noarchive",
            "h1": "Hire Dedicated Real Estate Virtual Assistants.",
            "h2s": "Book Your Free Strategy Session | Why Hire a Real Estate Virtual Assistant? | What Can a Real Estate Virtual Assistant Do? | How We Compare | Get Your Savings Report",
            "hero_copy_paraphrase": "Dedicated RE VA; grow brokerage/team revenue; cost cut; task list is RE-specific",
            "cta": "Book Your Free Strategy Session",
            "phone_prominence": "Not the primary CTA",
            "form_structure": "Same employer form + hidden click IDs",
            "primary_role": "real-estate VA / ISA / TC / admin / marketing",
            "industry": "real estate (agents, teams, brokers)",
            "geography": "US employer implied; talent geo not in H1",
            "employer_intent_theme": "industry hire; lead follow-up, ISA/prospecting, TC, listing admin",
            "proof_elements": "18 years; 70%; SOC 2; HIPAA; 0.7%; college; 4.9; rematch; US-hours language present",
            "offer_and_conversion": "Free strategy session + savings report",
            "internal_links": "Self-canonical; on-page form",
            "tracking_patterns": "Same GTM + UTM/gclid hidden fields",
            "probable_target_keyword": "real estate virtual assistants",
            "related_keyword_variations": "real estate virtual assistant; hire real estate VA; real estate ISA; transaction coordinator",
            "probable_campaign": "LM_US_Real_Estate_* (inferred from slug grammar, not observed UTM)",
            "probable_ad_group": "Real_Estate_Virtual_Assistants",
            "gad_campaignid_observed": "",
            "utm_term_observed": "",
            "match_type_inference": "phrase/exact on industry + VA; speculative",
            "page_type": "paid_industry_lp",
            "in_sitemap": "no (indexed sibling: /industries/real-estate-virtual-assistants/)",
            "evidence_source": "clean GET 2026-08-18; unique hash; RE H3 task list",
            "confidence": "observed (page) / high-confidence inference (keyword) / speculative (campaign name)",
        },
        {
            "full_url": "https://www.myoutdesk.com/lp/google-brand-search-campaign/",
            "clean_url": "https://www.myoutdesk.com/lp/google-brand-search-campaign/",
            "slug": "google-brand-search-campaign",
            "page_title": "Virtual Assistant Services | MyOutDesk",
            "meta_description": "Increase productivity by 25% and reduce overhead costs by up to 70% with high-quality, experienced virtual assistants.",
            "canonical_url": "https://www.myoutdesk.com/lp/google-brand-search-campaign/",
            "index_status": "noindex, nofollow, noarchive",
            "h1": "The Trusted Leader in Virtual Assistant Services .",
            "h2s": "Let's Work Together | Make MyOutDesk your strategic partner for outsourcing | How we compare | How it works",
            "hero_copy_paraphrase": "Brand-leader claim; outsourcing partner; same role grid as generic/PH templates",
            "cta": "On-page strategy form (same SDK)",
            "phone_prominence": "Not the primary CTA",
            "form_structure": "Same employer form + hidden click IDs",
            "primary_role": "general VA",
            "industry": "cross-industry",
            "geography": "unspecified",
            "employer_intent_theme": "brand navigational; already knows MyOutDesk",
            "proof_elements": "8,500+; $140M; 18 years; 70%; SOC 2; HIPAA; 0.7%; college; 4.9; rematch",
            "offer_and_conversion": "Strategy / partner form",
            "internal_links": "Self-canonical",
            "tracking_patterns": "Same stack",
            "probable_target_keyword": "myoutdesk",
            "related_keyword_variations": "my out desk; myoutdesk virtual assistant; myoutdesk reviews",
            "probable_campaign": "Brand Search (slug is explicit)",
            "probable_ad_group": "Brand_Search or Brand",
            "gad_campaignid_observed": "",
            "utm_term_observed": "",
            "match_type_inference": "exact brand",
            "page_type": "paid_brand_lp",
            "in_sitemap": "no",
            "evidence_source": "clean GET 2026-08-18; slug names the campaign type",
            "confidence": "observed (page + campaign-type slug)",
        },
        {
            "full_url": "https://www.myoutdesk.com/lp/google-brand-search-campaign-b/",
            "clean_url": "https://www.myoutdesk.com/lp/google-brand-search-campaign-b/",
            "slug": "google-brand-search-campaign-b",
            "page_title": "Virtual Assistant Services | MyOutDesk",
            "meta_description": "Increase productivity by 25% and reduce overhead costs by up to 70% with high-quality, experienced virtual assistants.",
            "canonical_url": "https://www.myoutdesk.com/lp/google-brand-search-campaign-b/",
            "index_status": "noindex, nofollow, noarchive",
            "h1": "You Searched MyOutDesk, You're in the Right Place.",
            "h2s": "Book Your Free Strategy Session | Why Hire a Virtual Assistant? | Your Path to Productivity | Stringent Talent Matching Process | How We Compare",
            "hero_copy_paraphrase": "Explicit brand-SERP handshake; 18+ years; full-time dedicated VAs; security/compliance heavier than PH LP",
            "cta": "Book a Strategy Call / Book Your Free Strategy Session / Get Your Report",
            "phone_prominence": "Not the primary CTA",
            "form_structure": "Same employer form + hidden click IDs; longer page (662k) with comparison table",
            "primary_role": "general VA + named functions (accounting, HR, executive support)",
            "industry": "cross-industry / regulated-industry security claims",
            "geography": "US & PH legal entities claimed on comparison table",
            "employer_intent_theme": "brand navigational; challenger vs freelancer/marketplace",
            "proof_elements": "18+ years; 8,500+; $140M; 4.9/304 reviews; 6-stage vetting 0.7%; college required; rematch; SOC 2; HIPAA; CIS Level 2; PCI-DSS; NDA; 1-week hire claim",
            "offer_and_conversion": "Free strategy session + state savings report",
            "internal_links": "Self-canonical",
            "tracking_patterns": "Same stack; public search previously exposed gad_campaignid=12320808679 (not re-requested)",
            "probable_target_keyword": "myoutdesk",
            "related_keyword_variations": "myoutdesk reviews; myoutdesk virtual assistant",
            "probable_campaign": "Brand Search (variant B / challenger layout)",
            "probable_ad_group": "Brand_Search_B",
            "gad_campaignid_observed": "12320808679 (from indexed URL; not re-requested)",
            "utm_term_observed": "",
            "match_type_inference": "exact brand",
            "page_type": "paid_brand_lp_variant",
            "in_sitemap": "no",
            "evidence_source": "indexed URL + clean GET 2026-08-18",
            "confidence": "observed",
        },
    ]
    path = OUT / "myoutdesk-paid-landing-pages.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def write_keywords_csv() -> None:
    rows = [
        # Directly observed
        {
            "keyword_cluster": "ph_va_geo",
            "competitor_keyword_observed": "virtual assistant in the philippines",
            "competitor_keyword_inferred": "",
            "recommended_vc_keyword": "virtual assistant philippines",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "medium (bare VA + country can leak jobs)",
            "estimated_volume_cpc": "not pulled (no Keyword Planner / Semrush this pass)",
            "vc_overlap": "yes — Offshore_VA_PH bids virtual assistant philippines / philippines va; search terms include offshore virtual assistants",
            "vc_current_lp": "https://www.virtualcoworker.app/us",
            "recommended_action": "build now",
            "evidence": "utm_term=virtual assistant in the philippines_e on seed click; LP slug/title/H1 match",
            "confidence": "observed",
        },
        {
            "keyword_cluster": "ph_va_geo",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "philippines virtual assistants",
            "recommended_vc_keyword": "philippines virtual assistant",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "medium",
            "estimated_volume_cpc": "",
            "vc_overlap": "yes — Offshore_VA_PH",
            "vc_current_lp": "https://www.virtualcoworker.app/us",
            "recommended_action": "build now",
            "evidence": "LP title + slug google-philippines-virtual-assistants",
            "confidence": "high-confidence inference",
        },
        {
            "keyword_cluster": "generic_va",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "virtual assistants",
            "recommended_vc_keyword": "virtual assistants",
            "suggested_match_type": "Exact (only if already live; else ignore/negative-watch)",
            "employer_intent_strength": "medium",
            "jobseeker_contamination_risk": "high",
            "estimated_volume_cpc": "VC already paused some general VA Exact junk on Hire_VA_PH",
            "vc_overlap": "yes — Hire_VA_PH has/had virtual assistant(s); ST includes virtual assistant jobs",
            "vc_current_lp": "https://www.virtualcoworker.app/us",
            "recommended_action": "ignore",
            "evidence": "dedicated LP /lp/google-virtual-assistants/; VC ST already showed job leakage on bare VA",
            "confidence": "high-confidence inference",
        },
        {
            "keyword_cluster": "outsourcing",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "virtual assistants outsourcing",
            "recommended_vc_keyword": "virtual assistant outsourcing philippines",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "low-medium",
            "estimated_volume_cpc": "",
            "vc_overlap": "yes — agency-intent add + Offshore_VA_PH outsourcing terms",
            "vc_current_lp": "https://www.virtualcoworker.app/us",
            "recommended_action": "build now",
            "evidence": "utm_campaign=LM_US_Virtual_Assistants_Outsourcing; utm_content=Virtual_Assistants_Outsourcing. Dedicated outsourcing slug 404'd.",
            "confidence": "high-confidence inference (campaign name) / observed (no dedicated LP)",
        },
        {
            "keyword_cluster": "agency_firm",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "virtual assistant agency",
            "recommended_vc_keyword": "virtual assistant agency",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "very high",
            "jobseeker_contamination_risk": "low",
            "estimated_volume_cpc": "US CORE buyer signal on Executive",
            "vc_overlap": "yes — VA_Agency_Firm_PH / Agency_PH; ST: virtual assistant agency, va company",
            "vc_current_lp": "https://www.virtualcoworker.app/us (staffing candidate /us/staffing not Ads dest)",
            "recommended_action": "build now",
            "evidence": "VC proven ST. MOD /lp/google-virtual-assistant-agency/ = 404. They sell agency-like managed VA without an agency-named paid LP.",
            "confidence": "observed (404) / high-confidence inference (VC overlap)",
        },
        {
            "keyword_cluster": "staffing",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "remote staffing agency",
            "recommended_vc_keyword": "remote staffing agency",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "very high",
            "jobseeker_contamination_risk": "medium (temp/remote job bleed — VC ST already shows this)",
            "estimated_volume_cpc": "US CORE clicks exist; ST includes remote temp agency junk",
            "vc_overlap": "yes — Staffing_Agency_PH / Agency_PH top ST",
            "vc_current_lp": "https://www.virtualcoworker.app/us ; /us/staffing candidate only",
            "recommended_action": "build now",
            "evidence": "VC Executive buyer signal. MOD /lp/google-remote-staffing-agency/ = 404. Need negatives: temp, job, remote work.",
            "confidence": "observed (404) / observed (VC ST)",
        },
        {
            "keyword_cluster": "real_estate",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "real estate virtual assistants",
            "recommended_vc_keyword": "real estate virtual assistant",
            "suggested_match_type": "Exact then Phrase",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "low-medium",
            "estimated_volume_cpc": "not pulled; US restructure marked Real Estate = WATCH",
            "vc_overlap": "page exists /us/real-estate; not an Ads destination yet",
            "vc_current_lp": "https://www.virtualcoworker.app/us/real-estate (do not point ads until measurement works)",
            "recommended_action": "controlled test",
            "evidence": "MOD dedicated paid LP confirmed. VC page exists; 18 Aug restructure says WATCH.",
            "confidence": "observed (MOD LP) / observed (VC LP status)",
        },
        {
            "keyword_cluster": "bookkeeping",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "bookkeeping virtual assistant",
            "recommended_vc_keyword": "bookkeeping virtual assistant",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "low",
            "estimated_volume_cpc": "GA4 10–16 Aug: /us/bookkeeping 40 sessions, 47.5% engaged — top role LP",
            "vc_overlap": "yes — Bookkeeping_Hire_PH; strongest role traffic",
            "vc_current_lp": "https://www.virtualcoworker.app/us/bookkeeping",
            "recommended_action": "build now",
            "evidence": "MOD role listed on paid LPs; /lp/google-bookkeeping/ and bookkeeping-virtual-assistants 404. VC already has the dedicated page + traffic.",
            "confidence": "observed (VC GA4 + MOD 404 + role grid)",
        },
        {
            "keyword_cluster": "customer_service",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "customer service virtual assistant",
            "recommended_vc_keyword": "virtual assistant customer service",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "medium (CSR job titles)",
            "estimated_volume_cpc": "GA4 /us/customer-service 22 sessions, 68.2% engaged — best role engagement",
            "vc_overlap": "yes — Customer_Service_Hire_PH / Outsource_PH",
            "vc_current_lp": "https://www.virtualcoworker.app/us/customer-service",
            "recommended_action": "build now",
            "evidence": "MOD lists CS on paid LPs; no dedicated paid LP. VC role page already converting attention.",
            "confidence": "observed",
        },
        {
            "keyword_cluster": "sales_setter",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "inside sales virtual assistant",
            "recommended_vc_keyword": "virtual appointment setter",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "medium-high (setter jobs)",
            "estimated_volume_cpc": "GA4 /us/sales 19 sessions, 63.2% engaged",
            "vc_overlap": "yes — Sales_Hire_PH / Appointment_Setter_Hire_PH; ST: appointment setter, remote setters",
            "vc_current_lp": "https://www.virtualcoworker.app/us/sales",
            "recommended_action": "controlled test",
            "evidence": "MOD RE LP heavily ISA/cold-call; generic LPs list Inside Sales & SDR. No /lp/google-inside-sales-agent/. VC restructure said pause setters — keep evidence, do not expand yet.",
            "confidence": "high-confidence inference",
        },
        {
            "keyword_cluster": "admin_ea",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "executive assistant philippines",
            "recommended_vc_keyword": "virtual executive assistant philippines",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "medium",
            "estimated_volume_cpc": "GA4 /us/administrative-support 14 sessions, 21.4% engaged — weakest role",
            "vc_overlap": "yes — Administration_EA_PH; ST: remote executive assistant, virtual administrative assistant",
            "vc_current_lp": "https://www.virtualcoworker.app/us/administrative-support",
            "recommended_action": "controlled test",
            "evidence": "MOD lists EA/admin on every generic paid LP; no dedicated paid LP. VC admin LP engagement is poor — fix page before more spend.",
            "confidence": "observed (GA4 + 404)",
        },
        {
            "keyword_cluster": "marketing",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "marketing virtual assistants",
            "recommended_vc_keyword": "digital marketing virtual assistant",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "medium-high",
            "jobseeker_contamination_risk": "medium",
            "estimated_volume_cpc": "GA4 /us/digital-marketing 17 sess 29.4% eng; /us/social-media 15 / 40%",
            "vc_overlap": "yes — Digital_Marketing_* / Social_Media_*",
            "vc_current_lp": "https://www.virtualcoworker.app/us/digital-marketing",
            "recommended_action": "controlled test",
            "evidence": "MOD lists Marketing VA; /lp/google-marketing-virtual-assistants/ 404. VC marketing LP engagement is soft.",
            "confidence": "observed",
        },
        {
            "keyword_cluster": "brand",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "myoutdesk",
            "recommended_vc_keyword": "virtual coworker",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high (navigational)",
            "jobseeker_contamination_risk": "low",
            "estimated_volume_cpc": "",
            "vc_overlap": "Brand_VC exists; Brand deferred",
            "vc_current_lp": "https://www.virtualcoworker.app/us",
            "recommended_action": "ignore",
            "evidence": "Two MOD brand LPs + gad_campaignid 12320808679. VC Brand deferred — do not center Stage 1 on this.",
            "confidence": "observed (MOD) / policy (VC brand deferred)",
        },
        {
            "keyword_cluster": "jobseeker_contamination",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "virtual assistant jobs / become a virtual assistant",
            "recommended_vc_keyword": "(negative) job, jobs, salary, career, apply, hiring, work from home",
            "suggested_match_type": "Negative Exact/Phrase",
            "employer_intent_strength": "none (talent-side)",
            "jobseeker_contamination_risk": "very high",
            "estimated_volume_cpc": "VC Hire_VA_PH ST: virtual assistant jobs; early US Zoho: 1 junk job-seeker",
            "vc_overlap": "Recruitment_Hire_PH keywords include virtual assistant companies hiring — pause/ignore",
            "vc_current_lp": "should never be /us hire form",
            "recommended_action": "negative",
            "evidence": "MOD /careers/ splits ZipRecruiter (US corp) vs MyOutDesk Philippines (VA applicants). Paid LPs are employer-only forms.",
            "confidence": "observed",
        },
        {
            "keyword_cluster": "filipino_va",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "filipino virtual assistants",
            "recommended_vc_keyword": "filipino virtual assistant agency",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "medium",
            "estimated_volume_cpc": "",
            "vc_overlap": "yes — Offshore_VA_PH / VA_Agency_Firm_PH",
            "vc_current_lp": "https://www.virtualcoworker.app/us",
            "recommended_action": "controlled test",
            "evidence": "MOD PH LP uses Philippines not Filipino in slug/title. /lp/google-filipino-virtual-assistants/ 404. VC already uses Filipino in on-page copy.",
            "confidence": "observed (404) / high-confidence inference",
        },
        {
            "keyword_cluster": "accounting",
            "competitor_keyword_observed": "",
            "competitor_keyword_inferred": "accounting virtual assistant",
            "recommended_vc_keyword": "virtual assistant accounting",
            "suggested_match_type": "Exact",
            "employer_intent_strength": "high",
            "jobseeker_contamination_risk": "medium (CPA/job bleed — VC ST has cpa virginia, filipino accountant near me)",
            "estimated_volume_cpc": "",
            "vc_overlap": "yes — Accounting_Hire_PH / Outsource_PH; /us/accounting exists",
            "vc_current_lp": "https://www.virtualcoworker.app/us/accounting",
            "recommended_action": "controlled test",
            "evidence": "MOD brand-b lists Accounting & Bookkeeping as a function, not a dedicated paid LP.",
            "confidence": "high-confidence inference",
        },
    ]
    path = OUT / "myoutdesk-inferred-keywords.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def write_campaign_map(tested: int, confirmed: int, candidates: int) -> None:
    data = {
        "generated_at_utc": utc_now(),
        "advertiser": "MyOutDesk, LLC",
        "public_site": "https://www.myoutdesk.com/",
        "stack_observed": {
            "cms": "Astro (not WordPress; /wp-json/ is HTML 404)",
            "gtm": "GTM-N589823",
            "ab": "GrowthBook",
            "forms": "Conversion.ai + ChiliPiper chat + Fillout savings report on pricing",
            "consent": "CookieYes",
            "other": ["Microsoft Clarity e4i40pe530", "LinkedIn Insight 7070116", "Clutch widget"],
        },
        "naming_conventions": {
            "paid_lp_grammar": "/lp/google-{theme}/",
            "confirmed_themes": [
                "philippines-virtual-assistants",
                "virtual-assistants",
                "real-estate-virtual-assistants",
                "brand-search-campaign",
                "brand-search-campaign-b",
            ],
            "learned": [
                "Prefix google- is required for these paid LPs; unprefixed /lp/{theme}/ not validated as a live family",
                "Country-first + plural service: philippines-virtual-assistants (singular and reversed word order 404)",
                "Industry-first + plural VA: real-estate-virtual-assistants (most other industry slugs 404)",
                "Head-term plural: virtual-assistants",
                "Brand family uses campaign-type slugs, including a -b challenger",
                "utm_campaign LM_US_{Theme}_{Angle}; utm_content {Theme}_{Angle}; utm_term {keyword}_{e|?}; utm_placement=c",
                "LM likely = Lead Management / Lead Magnet style prefix; US geo; not proven beyond this click",
                "Match-type suffix _e on utm_term = high-confidence exact",
            ],
            "sitemap_is_not_paid": "368 sitemap URLs; 0 /lp/. Paid LPs are noindex and excluded.",
        },
        "campaigns": [
            {
                "name": "LM_US_Virtual_Assistants_Outsourcing",
                "confidence": "high-confidence inference",
                "evidence": [
                    "utm_campaign on original seed click (analyzed locally; URL not re-requested with params)",
                    "utm_content=Virtual_Assistants_Outsourcing",
                    "utm_term=virtual assistant in the philippines_e",
                    "utm_placement=c",
                    "gad_campaignid=23338767511",
                    "Final URL /lp/google-philippines-virtual-assistants/",
                ],
                "network": "Google Search (inferred from /lp/google-* + gad_campaignid + utm_placement=c)",
                "geo": "US",
                "ad_groups": [
                    {
                        "name": "Virtual_Assistants_Outsourcing",
                        "confidence": "high-confidence inference",
                        "evidence": "utm_content",
                    }
                ],
                "keywords": [
                    {
                        "keyword": "virtual assistant in the philippines",
                        "match_type": "exact",
                        "confidence": "high-confidence inference",
                        "evidence": "utm_term suffix _e",
                    }
                ],
                "landing_page": "https://www.myoutdesk.com/lp/google-philippines-virtual-assistants/",
            },
            {
                "name": "Brand Search (official name unknown)",
                "confidence": "high-confidence inference",
                "evidence": [
                    "Live LPs named google-brand-search-campaign and google-brand-search-campaign-b",
                    "H1 on -b is an explicit brand-SERP handshake",
                    "Indexed URL previously exposed gad_campaignid=12320808679 on -b (not re-requested)",
                ],
                "network": "Google Search",
                "geo": "US (inferred; Transparency Center HTML is an app shell with no creatives this pass)",
                "ad_groups": [
                    {"name": "Brand / Brand_B", "confidence": "speculative", "evidence": "two distinct brand LP layouts"}
                ],
                "keywords": [
                    {"keyword": "myoutdesk", "match_type": "exact", "confidence": "high-confidence inference", "evidence": "LP H1 + slug"}
                ],
                "landing_pages": [
                    "https://www.myoutdesk.com/lp/google-brand-search-campaign/",
                    "https://www.myoutdesk.com/lp/google-brand-search-campaign-b/",
                ],
            },
            {
                "name": "LM_US_Virtual_Assistants (generic; name not observed)",
                "confidence": "speculative",
                "evidence": ["Live /lp/google-virtual-assistants/ noindex paid template"],
                "landing_page": "https://www.myoutdesk.com/lp/google-virtual-assistants/",
            },
            {
                "name": "LM_US_Real_Estate_* (name not observed)",
                "confidence": "speculative",
                "evidence": [
                    "Live /lp/google-real-estate-virtual-assistants/",
                    "Public indexed sibling /industries/real-estate-virtual-assistants/",
                ],
                "landing_page": "https://www.myoutdesk.com/lp/google-real-estate-virtual-assistants/",
            },
        ],
        "public_ia_not_paid_lps": {
            "services": [
                "administrative-virtual-assistants",
                "ai",
                "bookkeeping",
                "customer-service-virtual-assistant",
                "help-desk-outsourcing",
                "inside-sales-agent",
                "loan-processor-assistant",
                "marketing-virtual-assistants",
                "medical-billing-virtual-assistant",
                "real-estate-isa",
                "recruiting-assistant",
                "sales-development-representative",
                "transaction-coordinator",
                "virtual-medical-receptionist",
                "virtual-personal-assistant",
                "virtual-receptionist",
            ],
            "industries": [
                "ecommerce",
                "financial-planning",
                "healthcare",
                "hr",
                "insurance",
                "legal",
                "marketing-agency",
                "mortgage",
                "property-management",
                "real-estate-virtual-assistants",
                "tech",
            ],
            "regions_talent_hubs": ["africa", "apac", "latam"],
            "employer_conversion": ["/signup/", "/signup-discovery-call/", "/pricing/", "/enterprise/", "/contact/"],
            "jobseeker_split": {
                "url": "https://www.myoutdesk.com/careers/",
                "us_corporate": "ZipRecruiter",
                "va_applicants": "MyOutDesk Philippines apply path",
            },
            "note": "Mirrored /lp/google-{service|industry}/ for almost all sitemap slugs returned HTTP 404. Only real-estate-virtual-assistants exists as a paid twin.",
        },
        "discovery_stats": {
            "local_candidates_generated": candidates,
            "urls_tested_at_write": tested,
            "confirmed_paid_lps": confirmed,
            "ads_transparency": "Fetched adstransparency.google.com?region=US&domain=myoutdesk.com — Angular shell, no creatives in HTML (same as 18 Aug RE research).",
            "third_party_keyword_tools": "No Semrush/SpyFu/DataForSEO/SerpAPI credentials. Ads Keyword Planner not called (quota cap).",
        },
        "do_not_copy": "Do not reuse MyOutDesk proprietary sentences in VC ads. Facts only: strategy-call CTA pattern, PH geo LP, RE industry LP, brand variants, 70% savings claim (VC should not copy the claim).",
    }
    (OUT / "myoutdesk-campaign-map.json").write_text(json.dumps(data, indent=2), encoding="utf-8")


def main() -> None:
    probes = list(csv.DictReader((OUT / "myoutdesk-lp-probes.csv").open()))
    universe = json.loads((OUT / "candidate-universe.json").read_text())
    tested = len(probes)
    confirmed = sum(1 for r in probes if r.get("genuine_paid_lp") == "yes")
    write_lp_csv()
    write_keywords_csv()
    write_campaign_map(tested, confirmed, universe.get("total_candidates", 0))
    print(f"wrote package tested={tested} confirmed={confirmed} candidates={universe.get('total_candidates')}")


if __name__ == "__main__":
    main()
