"""Per-ad-group RSA challenger copy. Review-only — not uploaded.

15 headlines + 4 descriptions. No DKI in US (VA can mean Virginia).
Spell out Virtual Assistant in US. AU may use VA. No invented SLAs.
"""

from __future__ import annotations

# status: ready | needs_claim | leave
# action after approval: update_paused (cap) | create (under cap)

CHALLENGERS: list[dict] = [
    # ——— US CORE ———
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "Agency_PH",
        "status": "ready",
        "cluster": "staffing_agency",
        "path1": "staff",
        "path2": "agency",
        "headlines": [
            "Remote Staffing Agency",
            "Filipino Staffing Agency",
            "Philippines Staffing Partner",
            "Hire Philippines-Based Staff",
            "US Employers",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Dedicated Remote Staff",
            "Not a Freelance Marketplace",
            "Book a Hiring Consultation",
            "Staff Work Your US Hours",
            "You Keep Hire Control",
            "Since 2011",
            "Skip Temp Agency Guesswork",
            "A Staffing Firm. Not a Gig.",
        ],
        "descriptions": [
            "Remote staffing agency for US employers. Dedicated Filipino staff, not a freelance bench.",
            "We recruit and screen. You interview the shortlist. We handle payroll after you say yes.",
            "Philippines-based staff on your US hours. Book a hiring consultation - employers only.",
            "Not a temp marketplace. One dedicated seat, screened for your role, working your hours.",
        ],
        "why_ctr": "Search is 'remote staffing agency' / 'filipino staffing agency', not generic VA. Current ads still lean VA. This names the query.",
        "why_cvr": "Employer-only + you interview + payroll handled. Filters job-seekers and temp-agency shoppers leaking into this group.",
        "new_pct": 35,
        "lp": {
            "url": "https://www.virtualcoworker.app/us",
            "before_h1": "Hire Dedicated Virtual Assistants from the Philippines",
            "after_h1": "Hire Dedicated Virtual Assistants from the Philippines",
            "before_sub": "Full-time or part-time dedicated professionals who work your hours. We recruit, vet, handle payroll, and stay with you after they start. Serving businesses since 2011.",
            "after_sub": "A Philippines staffing partner for US employers. We recruit and screen. You interview the shortlist. Dedicated staff on your hours - not a freelance marketplace.",
            "note": "Same URL. One supporting subhead so agency queries still match the first screen.",
        },
    },
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "Offshore_VA_PH",
        "status": "ready",
        "cluster": "hire_va_ph",
        "path1": "philippines",
        "path2": "staff",
        "headlines": [
            "Philippines Virtual Assistant",
            "Hire a Filipino Teammate",
            "Filipino Virtual Assistant",
            "Outsource Without Freelancers",
            "Dedicated Remote Staff",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Philippines-Based Staff Hire",
            "On Your US Business Hours",
            "Not a Gig Marketplace",
            "Book a Hiring Consultation",
            "US Employers Hiring Only",
            "Staff Who Stay On Your Work",
            "Offshore Help That Stays",
            "You Meet Them Before Hire",
        ],
        "descriptions": [
            "Hire a Philippines virtual assistant as dedicated staff - not a rotating freelance bench.",
            "We recruit and screen Filipino talent. You interview. Nobody starts until you say yes.",
            "Outsource the seat, not the control. They work your US hours. We handle payroll.",
            "Book a hiring consultation. Employers only. Serving businesses since 2011.",
        ],
        "why_ctr": "Winning assets already say Philippines / Filipino / virtual staff (~18-28% CTR). Challenger spells that out without VA=Virginia DKI.",
        "why_cvr": "Anti-freelance + you interview vs Wing 'we interview for you'. Consultation CTA matches the LP.",
        "new_pct": 30,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "Staffing_Agency_PH",
        "status": "ready",
        "cluster": "staffing_agency",
        "path1": "remote",
        "path2": "staffing",
        "headlines": [
            "Remote Staffing Agency",
            "Remote Staffing Agencies",
            "Philippines Staffing Agency",
            "Hire Remote Staff. Properly.",
            "Dedicated Seats, Not Temps",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Not Upwork. Not a Temp App.",
            "US Hours. Filipino Staff.",
            "Book a Strategy Call",
            "Employers Hiring Remote Staff",
            "You Keep the Hire Decision",
            "Staffing Partner Since 2011",
            "Skip the Freelance Board",
            "One Person. Your Workflow.",
        ],
        "descriptions": [
            "Looking for a remote staffing agency? Dedicated Filipino staff for US teams - not temps.",
            "We recruit and screen. You interview the shortlist. We handle payroll and stay on after.",
            "Not Upwork and not a temp agency. One dedicated seat on your hours, matched to the role.",
            "Book a free strategy call. Employers only. Philippines-based staff, US business hours.",
        ],
        "why_ctr": "Exact query is 'remote staffing agency/agencies' (17% KW CTR). One existing RSA already uses that line; this one leads with it across more slots.",
        "why_cvr": "Draws a hard line vs temp-agency and Upwork searches leaking in. Consultation, not 'apply now'.",
        "new_pct": 30,
        "lp": {
            "url": "https://www.virtualcoworker.app/us",
            "before_h1": "Hire Dedicated Virtual Assistants from the Philippines",
            "after_h1": "Hire Dedicated Virtual Assistants from the Philippines",
            "before_sub": "Full-time or part-time dedicated professionals who work your hours. We recruit, vet, handle payroll, and stay with you after they start. Serving businesses since 2011.",
            "after_sub": "Remote staffing for US employers. Dedicated Philippines-based staff - we recruit and screen, you interview, we handle payroll. Not a temp agency.",
            "note": "Tiny subhead tweak so staffing-agency ads continue on the first screen.",
        },
    },
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "VA_Agency_Firm_PH",
        "status": "ready",
        "cluster": "va_agency",
        "path1": "agency",
        "path2": "hire",
        "headlines": [
            "Virtual Assistant Agency",
            "Virtual Assistant Company",
            "Virtual Assistant Firm",
            "Hire a Filipino Teammate",
            "Agency. Not a Marketplace.",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Dedicated Staff, Not Gigs",
            "Book a Hiring Consultation",
            "US Employers. Not Job Seekers.",
            "Philippines Talent. US Hours.",
            "You Choose Who Joins",
            "Staffing Firm Since 2011",
            "Skip Freelance Guesswork",
            "One Seat. Your Company.",
        ],
        "descriptions": [
            "A virtual assistant agency for US employers - dedicated Filipino staff, not a gig app.",
            "We recruit and screen. You interview. We handle payroll. Nobody starts until you pick.",
            "Looking for a VA firm? Book a hiring consultation. Employers only. Your hours, not theirs.",
            "Philippines-based dedicated staff. Serving businesses since 2011 - not a freelance board.",
        ],
        "why_ctr": "Keywords are agency / company / firm with almost no clicks yet. Current ads bury that language. This leads with the query.",
        "why_cvr": "Firm-not-marketplace + employer qualification. Volume is thin - directional, not a conversion proof.",
        "new_pct": 40,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_CORE",
        "ad_group": "Virtual_Staff_PH",
        "status": "ready",
        "cluster": "virtual_staff",
        "path1": "virtual",
        "path2": "staff",
        "headlines": [
            "Hire Virtual Staff",
            "Virtual Staff Philippines",
            "Dedicated Remote Staff",
            "Hire Philippines-Based Staff",
            "US Employers Hiring Staff",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Not Rotating Freelancers",
            "On Your US Business Hours",
            "Book a Hiring Consultation",
            "Filipino Staff for US Teams",
            "You Pick Who Joins",
            "Staffing Since 2011",
            "Skip the Job Board Pile",
            "One Teammate. Your Hours.",
        ],
        "descriptions": [
            "Hire virtual staff from the Philippines - dedicated to your company, not a freelance pool.",
            "We recruit and screen. You interview the shortlist. We handle payroll on US hours.",
            "Virtual staff who stay on your work. Book a hiring consultation. Employers only.",
            "Not a gig marketplace. One Philippines-based teammate, matched to the seat you need.",
        ],
        "why_ctr": "Query cluster is 'virtual staff' / 'hire virtual staff'. Existing ads are generic partner language. This matches the noun buyers type.",
        "why_cvr": "Employer-only + interview shortlist. Sample is tiny - do not treat as a conversion forecast.",
        "new_pct": 40,
        "lp": None,
    },
    # ——— US ROLES ———
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Administration_EA_PH",
        "status": "ready",
        "cluster": "admin_ea",
        "path1": "admin",
        "path2": "hire",
        "headlines": [
            "Hire a Virtual Assistant",
            "Filipino Virtual Assistant",
            "Hire Executive Assistant",
            "Inbox Eating Your Week?",
            "Dedicated Admin Teammate",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Philippines Admin Staff",
            "On Your US Business Hours",
            "Book a Strategy Call",
            "Not a Freelance Assistant",
            "US Employers Hiring Admin",
            "Calendar, Inbox, Follow-Ups",
            "You Meet Them First",
            "Admin Help That Stays",
        ],
        "descriptions": [
            "Inbox, calendar, and follow-ups eating your week? Hire a dedicated Filipino assistant.",
            "We recruit and screen. You interview. Typical admin around $8 an hour - employers only.",
            "Not a freelance assistant. One dedicated seat on your US hours. We handle payroll.",
            "Book a free strategy call. Executive assistant or virtual assistant - you choose the seat.",
        ],
        "why_ctr": "The live RSA is abbreviation-heavy (EA/PH) and sitting at 3.6% CTR. Search is virtual admin / remote EA / Filipino assistant. This matches those terms in plain English.",
        "why_cvr": "LP already sells $8 admin + you interview. Ad now continues that instead of 'Hire Executive Assistant' jargon.",
        "new_pct": 35,
        "claims": ["Typical admin around $8 an hour - already on the live admin LP. Confirm ops still stands behind it."],
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Accounting_Hire_PH",
        "status": "ready",
        "cluster": "accounting",
        "path1": "accounting",
        "path2": "support",
        "headlines": [
            "Hire Accounting Support",
            "Filipino Accounting Staff",
            "Month-End Piling Up?",
            "Dedicated Accounting Seat",
            "Philippines Accounting Hire",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Not Licensed CPA Advice",
            "On Your Close Calendar",
            "Book a Hiring Consultation",
            "US Finance Teams",
            "AP and AR Support Staff",
            "You Interview Before Hire",
            "Skip Freelance Book Tasks",
            "Extra Capacity. Your Tools.",
        ],
        "descriptions": [
            "Month-end piling up? Hire dedicated Filipino accounting support - not a freelance gig.",
            "We recruit and screen. You interview. Extra capacity for the work - not licensed advice.",
            "Philippines accounting staff on your hours. Book a hiring consultation. Employers only.",
            "A dedicated finance seat for recurring work. You pick who joins. We handle payroll.",
        ],
        "why_ctr": "Enabled ads have 0 clicks on 27 impressions. Headlines over-index 'accountant' (sounds like a CPA). Search is accounting support / VA for accounting.",
        "why_cvr": "LP already says extra capacity, not licensed advice. Ad now matches that so CPAs and job-seekers bounce less.",
        "new_pct": 40,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Bookkeeping_Hire_PH",
        "status": "ready",
        "cluster": "bookkeeping",
        "path1": "books",
        "path2": "hire",
        "headlines": [
            "Hire a Filipino Bookkeeper",
            "Virtual Bookkeeping Help",
            "Bookkeeping Virtual Assistant",
            "Dedicated Books Seat",
            "Invoices Stacking Up?",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Philippines Bookkeeping Staff",
            "On Your Finance Hours",
            "Book a Strategy Call",
            "Not Freelance Book Tasks",
            "US Employers Hiring Books",
            "Reconciliations Off Your Desk",
            "You Meet Them First",
            "Same Bookkeeper Every Week",
        ],
        "descriptions": [
            "Invoices stacking up? Hire a dedicated Filipino bookkeeper - not a freelance task board.",
            "We recruit and screen. You interview. We handle payroll. Tell us the tools you use.",
            "Virtual bookkeeping for US teams. Book a strategy call. Employers only. Your hours.",
            "A books seat that stays. Reconciliations and invoices - you pick who joins.",
        ],
        "why_ctr": "Keywords are 'virtual assistant bookkeeping' / 'bookkeeping virtual assistant' (17% and 10% CTR). One live ad uses DKI Hire Bookkeeper; this names the search language.",
        "why_cvr": "Dedicated seat vs freelance bookkeeping. Does not claim QuickBooks ProAdvisor.",
        "new_pct": 30,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Customer_Service_Hire_PH",
        "status": "ready",
        "cluster": "cs_hire",
        "path1": "support",
        "path2": "hire",
        "headlines": [
            "Hire Customer Service Staff",
            "Filipino Support Teammate",
            "Customers Waiting Too Long?",
            "Dedicated Support Seat",
            "Philippines Customer Service",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Not a WFH Job Ad",
            "On Your Support Hours",
            "Book a Hiring Consultation",
            "US Businesses Hiring Support",
            "Same Agent. Not a Bench.",
            "You Interview Before Hire",
            "Skip Freelance Chat Gigs",
            "Support That Knows Your Brand",
        ],
        "descriptions": [
            "Customers waiting too long? Hire dedicated Filipino support on US hours - not a job ad.",
            "We recruit and screen. You interview. One support seat, not a rotating freelance bench.",
            "Philippines customer service staff for US businesses. Book a hiring consultation.",
            "Employers only. We handle payroll after you pick. Serving businesses since 2011.",
        ],
        "why_ctr": "Live CTR ~6%. Search terms are full of WFH job-seeker queries. This says businesses hiring support, not 'representative jobs'.",
        "why_cvr": "Hard employer qualification should lift qualified rate even if raw CTR stays modest.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Customer_Service_Outsource_PH",
        "status": "ready",
        "cluster": "cs_outsource",
        "path1": "outsource",
        "path2": "support",
        "headlines": [
            "Outsource Customer Service",
            "Outsource Customer Support",
            "Dedicated Support Seat",
            "Philippines Support Staff",
            "Not a Call-Center Bench",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "US Hours. Filipino Support.",
            "Book a Strategy Call",
            "Employers Outsourcing Support",
            "Same Person on Your Queue",
            "You Keep Brand Control",
            "Skip Gig Support Apps",
            "Helpdesk Seat. Not a BPO Pit.",
            "You Meet Them Before Go-Live",
        ],
        "descriptions": [
            "Outsource customer service to a dedicated Filipino teammate - not a call-center bench.",
            "We recruit and screen. You interview. They work your US hours. We handle payroll.",
            "You want a vendor who staffs a person. You interview. They stay on your queue.",
            "Book a strategy call. Employers only. Dedicated support seat, not a gig pool.",
        ],
        "why_ctr": "Exact 'outsource customer service' plus live term 'cs outsource' (3 clicks). Current ads are generic PH outsourcing jargon.",
        "why_cvr": "Positions vs BPO benches: you interview the person. Better qualified click than a call-center shopper.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Digital_Marketing_Hire_PH",
        "status": "ready",
        "cluster": "marketing",
        "path1": "marketing",
        "path2": "hire",
        "headlines": [
            "Hire a Filipino Marketer",
            "Remote Marketing Assistant",
            "Marketing Virtual Assistant",
            "Digital Marketing Staff",
            "Your Marketing Is Stalled",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Dedicated Marketing Seat",
            "On Your US Campaign Hours",
            "Book a Strategy Call",
            "Not a Freelance Marketer",
            "US Teams Hiring Marketing",
            "Campaigns, Reporting, Ops",
            "You Meet Them First",
            "Philippines Marketing Hire",
        ],
        "descriptions": [
            "Need a remote marketing assistant? Hire a dedicated Filipino marketer for US hours.",
            "We recruit and screen. You interview. Campaigns, reporting, and content ops get an owner.",
            "Not a freelance marketer. One marketing seat. Book a free strategy call. Employers only.",
            "Digital marketing staff from the Philippines - you pick who joins. We handle payroll.",
        ],
        "why_ctr": "Best keyword is 'remote marketing assistant' at 29.6% CTR. Live ads say 'Hire Digital Marketing VA'. This uses the winning query.",
        "why_cvr": "LP H1 already matches stalled marketing + Filipino marketer. Consultation CTA is the same as MyOutDesk without copying them.",
        "new_pct": 30,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Digital_Marketing_Outsource_PH",
        "status": "ready",
        "cluster": "marketing",
        "path1": "outsource",
        "path2": "marketing",
        "headlines": [
            "Outsource Marketing Work",
            "Philippines Marketing Staff",
            "Dedicated Marketing Seat",
            "Not a PH Marketing Agency",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Same Marketer Every Day",
            "On Your US Hours",
            "Book a Hiring Consultation",
            "US Brands Outsourcing Ops",
            "Campaign Ops Without Churn",
            "You Keep Strategy In-House",
            "Skip Freelance Marketing",
            "Offshore Seat. Your Tools.",
            "You Interview Before Hire",
        ],
        "descriptions": [
            "Outsource marketing ops to a dedicated Filipino marketer - not a PH agency retainer.",
            "We recruit and screen. You interview. Your strategists stay on judgment work.",
            "Not a Philippines agency retainer. A dedicated marketer you interview for the seat.",
            "Book a hiring consultation. Employers only. Same marketer, your hours, we handle payroll.",
        ],
        "why_ctr": "Search terms are 'digital marketing agency philippines' - buyers think agency. Ad clarifies dedicated staff vs agency retainer.",
        "why_cvr": "Stops agency-shoppers who wanted a PH shop, keeps employers who want a person on their team.",
        "new_pct": 40,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Appointment_Setter_Hire_PH",
        "status": "ready",
        "cluster": "sales",
        "path1": "setter",
        "path2": "hire",
        "headlines": [
            "Hire Appointment Setter",
            "Virtual Appointment Setter",
            "Filipino Appointment Setter",
            "Dedicated Setter Seat",
            "Calendar Still Empty?",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Not a WFH Setter Job",
            "On Your Sales Hours",
            "Book a Strategy Call",
            "US Teams Hiring Setters",
            "You Meet Them Before Hire",
            "Skip Freelance Setters",
            "Pipeline Support That Stays",
            "Philippines Sales Support",
        ],
        "descriptions": [
            "Hire a virtual appointment setter as dedicated Filipino sales support - not a WFH job ad.",
            "We recruit and screen. You interview. They work your sales hours. We handle payroll.",
            "Employers only. Book a strategy call. Nobody starts until you say yes.",
            "Not freelance setters. One dedicated seat for calendar, follow-up, and booking.",
        ],
        "why_ctr": "Live RSA already at 21% CTR. Keyword 'virtual appointment setter' is the money term. Challenger keeps that and adds employer qualification vs WFH.",
        "why_cvr": "Sales LP already says setter / you interview. This should cut job-seeker clicks that look like CTR.",
        "new_pct": 30,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Sales_Hire_PH",
        "status": "ready",
        "cluster": "sales",
        "path1": "sales",
        "path2": "support",
        "headlines": [
            "Hire Sales Support Staff",
            "Virtual Appointment Setter",
            "Filipino Sales Assistant",
            "Follow-Ups Still Slipping?",
            "Dedicated Sales Seat",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Not a WFH Setter Job",
            "On Your Sales Hours",
            "Book a Hiring Consultation",
            "US Teams Hiring Sales Help",
            "CRM, Research, Follow-Up",
            "You Interview",
            "Skip Freelance Outbound",
            "Pipeline Help That Stays",
        ],
        "descriptions": [
            "Follow-ups slipping? Dedicated Filipino sales support for setting, CRM, and research.",
            "We recruit and screen. You interview. Not a work-from-home setter job. Employers only.",
            "Book a hiring consultation. They work your sales hours. We handle payroll.",
            "A dedicated sales seat so sellers spend time talking to buyers - not chasing admin.",
        ],
        "why_ctr": "Live CTR ~5%. Search is flooded with WFH appointment-setter jobs. Current ads do not say employers only.",
        "why_cvr": "Qualification in the headline should drop junk clicks and lift consult rate among remaining clicks.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Social_Media_Hire_PH",
        "status": "ready",
        "cluster": "social",
        "path1": "social",
        "path2": "hire",
        "headlines": [
            "Hire Social Media Staff",
            "Social Media Virtual Assistant",
            "Filipino Social Teammate",
            "Brand Going Quiet?",
            "Dedicated Social Seat",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Virtual Social Media Manager",
            "On Your Brand Hours",
            "Book a Strategy Call",
            "Not a Freelance Poster",
            "US Brands Hiring Social",
            "Scheduling and Community",
            "You Meet Them First",
            "Philippines Social Support",
        ],
        "descriptions": [
            "Brand going quiet? Hire a dedicated Filipino social teammate - not a freelance poster.",
            "Social media virtual assistant for US brands. We recruit and screen. You interview.",
            "Book a strategy call. Scheduling, community, assets. They work your hours. Employers only.",
            "One social seat that stays. You pick who joins. We handle payroll after you say yes.",
        ],
        "why_ctr": "Only one enabled RSA at 5.6% CTR. Keywords 'social media virtual assistant' and 'virtual social media manager' are unused in the live ad.",
        "why_cvr": "LP already matches. Employer-only line should cut remote-SMM job clicks.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Recruitment_Hire_PH",
        "status": "ready",
        "cluster": "recruiting",
        "path1": "recruiting",
        "path2": "help",
        "headlines": [
            "Hire Recruiting Support",
            "Virtual Recruiting Assistant",
            "Dedicated Recruiting Help",
            "Filipino Screening Support",
            "Hiring Pipeline Slowing?",
            "You Interview the Shortlist",
            "Not a Jobs Board Hire",
            "Sourcing and Screening Help",
            "On Your Hiring Hours",
            "Book a Strategy Call",
            "US TA Teams Hiring Help",
            "ATS and Interview Scheduling",
            "TA Teams. Not Job Seekers",
            "Skip Freelance Sourcers",
            "Philippines Recruiting Staff",
        ],
        "descriptions": [
            "Need recruiting support - not a virtual assistant job? Dedicated Filipino screening help.",
            "We recruit and screen a recruiting teammate. You interview. Employers hiring only.",
            "Sourcing, screens, ATS admin, interview scheduling. Book a strategy call.",
            "This is not a jobs board. If you are hiring recruiters for your company, talk to us.",
        ],
        "why_ctr": "CTR looks fine (~18%) but terms are 'virtual assistant jobs'. Ads with {KeyWord:Hire Recruiting VA} will keep attracting seekers.",
        "why_cvr": "Plain 'employers only / not a jobs board' is the conversion play. Expect CTR to fall and quality to rise.",
        "new_pct": 40,
        "lp": None,
    },
    {
        "market": "US",
        "campaign": "VC_US_S_ROLES",
        "ad_group": "Human_Resources_Hire_PH",
        "status": "ready",
        "cluster": "hr",
        "path1": "hr",
        "path2": "hire",
        "headlines": [
            "Hire HR Support Staff",
            "HR Virtual Assistant",
            "Filipino People Ops Help",
            "People Admin Stacking Up?",
            "Dedicated HR Seat",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Onboarding and HR Docs",
            "On Your US Hours",
            "Book a Hiring Consultation",
            "US Employers Hiring HR Help",
            "Not a Freelance HR Gig",
            "You Interview Before Hire",
            "Philippines HR Support",
            "Managers Get Time Back",
        ],
        "descriptions": [
            "People admin stacking up? Dedicated Filipino HR support for onboarding and docs.",
            "HR virtual assistant for US employers. We recruit and screen. You interview the shortlist.",
            "Not a job ad. Book a hiring consultation. They work your hours. We handle payroll.",
            "A dedicated people-ops seat. You pick who joins. Serving businesses since 2011.",
        ],
        "why_ctr": "One enabled RSA, almost no clicks. Keyword is 'hr virtual assistant'. Live ad never says those words.",
        "why_cvr": "LP already matches people-admin stacking. Thin volume - directional only.",
        "new_pct": 40,
        "lp": None,
    },
    # ——— AU CORE ———
    {
        "market": "AU",
        "campaign": "VC_AU_S_CORE",
        "ad_group": "Agency_PH",
        "status": "ready",
        "cluster": "staffing_agency_au",
        "path1": "staffing",
        "path2": "hire",
        "headlines": [
            "Filipino Staffing Agency",
            "Philippines Staffing Agency",
            "Virtual Assistant Firm",
            "Hire Philippines-Based Staff",
            "Australian Employers Hiring",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Not a Freelance Marketplace",
            "Book a Hiring Consultation",
            "Dedicated Remote Staff",
            "You Keep Hire Control",
            "Staffing Partner Since 2011",
            "Skip the Job Board Hunt",
            "A Firm. Not a Gig App.",
        ],
        "descriptions": [
            "Filipino staffing agency for Australian businesses. Dedicated staff, Australian hours.",
            "We recruit and screen. You interview the shortlist. We handle employment admin.",
            "Not a freelance marketplace. Book a hiring consultation - obligation free.",
            "Philippines staff on Australian hours. You pick who joins. Nobody starts till you say yes.",
        ],
        "why_ctr": "Keywords are Filipino/Philippines staffing agency (26% and 21% CTR). Live ads still say 'Looking for a VA?'. This names the agency query.",
        "why_cvr": "AU buyers compare Outsourcing Angel and 24x7 Direct. Gap we own: you interview, Australian hours, since 2011 - not a Freedom Audit script.",
        "new_pct": 35,
        "lp": {
            "url": "https://www.virtualcoworker.app/au",
            "before_h1": "Hire dedicated virtual assistants from the Philippines",
            "after_h1": "Hire dedicated virtual assistants from the Philippines",
            "before_sub": "Full-time or part-time dedicated professionals on Australian hours. We recruit, vet, handle employment admin, and stay with you after they start. Serving businesses since 2011.",
            "after_sub": "A Philippines staffing partner for Australian employers. We recruit and screen. You interview the shortlist. Dedicated staff on Australian hours - not a freelance marketplace.",
            "note": "Supporting subhead for agency-intent ads. No layout change.",
        },
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_CORE",
        "ad_group": "Hire_VA_PH",
        "status": "ready",
        "cluster": "hire_va_au",
        "path1": "hire",
        "path2": "va",
        "headlines": [
            "Hire a Virtual Assistant",
            "Hiring Virtual Assistant",
            "Hire Filipino VA",
            "Philippines Virtual Assistant",
            "On Australian Hours",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Dedicated Filipino Teammate",
            "Australian Employers Only",
            "Book a Hiring Consultation",
            "Not a Gig Marketplace",
            "VA for Hire Philippines",
            "You Interview. You Pick.",
            "Employment Admin Handled",
            "Since 2011 for AU Businesses",
        ],
        "descriptions": [
            "Hiring a virtual assistant in Australia? Dedicated Filipino teammate on Australian hours.",
            "We recruit and screen. You interview. We handle employment admin. Obligation-free chat.",
            "Not a gig marketplace and not a BPO bench. One person, your hours, you say yes first.",
            "Book a hiring consultation. Employers only. Philippines talent, Australian hours.",
        ],
        "why_ctr": "Already 17.9% CTR / 21% last two days. Challenger matches the live query 'hiring virtual assistant' and Australian hours more directly than PH-abbreviation ads.",
        "why_cvr": "Differentiates vs 24x7 Direct (full-time BPO, they manage) and Outsourcing Angel (Freedom Audit). VC: you interview the person.",
        "new_pct": 30,
        "lp": None,
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_CORE",
        "ad_group": "Offshore_VA_PH",
        "status": "ready",
        "cluster": "hire_va_au",
        "path1": "offshore",
        "path2": "au",
        "headlines": [
            "Offshore Virtual Assistant",
            "Hire Filipino Staff Offshore",
            "Philippines Virtual Assistant",
            "Dedicated Offshore Seat",
            "On Australian Hours",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "Not a 40-Hour BPO Lock-In",
            "Book a Hiring Consultation",
            "Australian Employers Hiring",
            "Offshore Help That Stays",
            "You Meet Them First",
            "Employment Admin Handled",
            "Not Freelance Offshore",
            "One Teammate. Your Hours.",
        ],
        "descriptions": [
            "Offshore virtual assistant for Australian businesses - dedicated Filipino staff.",
            "We recruit and screen. You interview. Part-time or full-time. We handle employment admin.",
            "Not a full-time-only BPO. Book an obligation-free hiring consultation. Employers only.",
            "Philippines talent on Australian hours. Nobody starts until you say yes.",
        ],
        "why_ctr": "Live enabled RSA has 0% CTR on 15 impressions. Query is 'offshore virtual assistant'. 24x7 Direct appears in terms.",
        "why_cvr": "24x7 is full-time-only managed BPO. VC can own part-time/full-time + you interview. Do not claim ISO or 70% savings.",
        "new_pct": 40,
        "lp": None,
    },
    # ——— AU ROLES ———
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Administration_EA_PH",
        "status": "ready",
        "cluster": "admin_ea_au",
        "path1": "admin",
        "path2": "hire",
        "headlines": [
            "Hire a Virtual Assistant",
            "Virtual Admin Assistant",
            "Filipino Assistant Hire",
            "Hire Executive Assistant",
            "Still Doing Admin Yourself?",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Dedicated Admin Teammate",
            "Book a Hiring Consultation",
            "Australian Employers Only",
            "Inbox, Calendar, Follow-Ups",
            "Not a Freelance Assistant",
            "You Meet Them First",
            "Employment Admin Handled",
        ],
        "descriptions": [
            "Still doing the admin yourself? Hire a dedicated Filipino assistant on Australian hours.",
            "Virtual admin assistant for Australian businesses. We recruit and screen. You interview.",
            "Not a BPO bench. Book an obligation-free chat. We handle employment admin after you pick.",
            "Inbox, scheduling, follow-ups. Employers only. Serving businesses since 2011.",
        ],
        "why_ctr": "Keyword 'virtual admin assistant' (53 impr / 11% CTR) is the cluster. Live RSA is EA/PH jargon. 24x7 Direct is the competitor query.",
        "why_cvr": "You-interview vs 24x7's managed BPO. LP already says Australian hours + you interview.",
        "new_pct": 35,
        "lp": {
            "url": "https://www.virtualcoworker.app/au/administrative-support",
            "before_h1": "Still doing the admin yourself? Hire a dedicated Filipino virtual assistant.",
            "after_h1": "Still doing the admin yourself? Hire a dedicated Filipino virtual assistant.",
            "before_sub": "Inbox, scheduling and follow-ups still landing back on you? We recruit. You interview. Australian hours - no lock-in from the first chat.",
            "after_sub": "Virtual admin assistant or executive assistant - we recruit and screen, you interview the shortlist. Dedicated Filipino staff on Australian hours. Not a BPO bench.",
            "note": "Subhead names the live query (virtual admin assistant) and the 24x7 contrast without naming them.",
        },
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Accounting_Hire_PH",
        "status": "ready",
        "cluster": "accounting",
        "path1": "accounting",
        "path2": "hire",
        "headlines": [
            "Hire Accounting Support",
            "Filipino Accounting Staff",
            "Month-End Still a Scramble?",
            "Dedicated Accounting Seat",
            "Hire Remote Accountant Help",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Not a Substitute Accountant",
            "Book a Hiring Consultation",
            "Australian Finance Teams",
            "AP and AR Support Staff",
            "You Interview Before Hire",
            "Employment Admin Handled",
            "Extra Capacity. Your Tools.",
        ],
        "descriptions": [
            "Month-end still a scramble? Dedicated Filipino accounting support on Australian hours.",
            "We recruit and screen. You interview. Extra capacity - not your accountant substitute.",
            "Hire remote accounting help for Australian businesses. Obligation-free. Employers only.",
            "A finance seat that stays. You pick who joins. We handle employment admin.",
        ],
        "why_ctr": "Live CTR 8% with DKI 'Hire Accountant' plus licensed-sounding lines. Query is hire remote accountant / Filipino accountant.",
        "why_cvr": "LP already disclaims licensed advice. Ad now matches so we don't over-promise CPA.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Bookkeeping_Hire_PH",
        "status": "ready",
        "cluster": "bookkeeping",
        "path1": "books",
        "path2": "hire",
        "headlines": [
            "Hire a Filipino Bookkeeper",
            "Bookkeeping Virtual Assistant",
            "Dedicated Books Seat",
            "Books Falling Behind?",
            "Philippines Bookkeeping Staff",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Not Freelance Book Tasks",
            "Book a Hiring Consultation",
            "Australian Teams Hiring Books",
            "Invoices Off Your Desk",
            "You Meet Them First",
            "Employment Admin Handled",
            "Same Bookkeeper Every Week",
        ],
        "descriptions": [
            "Books falling behind? Hire a dedicated Filipino bookkeeper on Australian hours.",
            "We recruit and screen. You interview. Name Xero or your stack in the brief.",
            "Bookkeeping virtual assistant for Australian businesses. Obligation-free. Employers only.",
            "Not a freelance task board. One books seat. You pick. We handle employment admin.",
        ],
        "why_ctr": "The other enabled RSA is junk ('Quickbooks Proadvisor', 'Save Time and Money w VAs'). This is the human challenger against that.",
        "why_cvr": "Does not repeat the trademark/ProAdvisor claim on the junk sibling RSA. Consultation + you interview.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Customer_Service_Hire_PH",
        "status": "ready",
        "cluster": "cs_hire",
        "path1": "support",
        "path2": "hire",
        "headlines": [
            "Hire Customer Support Staff",
            "Filipino Support Teammate",
            "Customers Waiting on Replies?",
            "Dedicated Support Seat",
            "Virtual Customer Service",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Not a Job Ad. Employers Only.",
            "Book a Hiring Consultation",
            "Same Agent. Not a Bench.",
            "You Meet Them First",
            "Employment Admin Handled",
            "Skip Freelance Chat Gigs",
            "Philippines Support Hire",
        ],
        "descriptions": [
            "Customers waiting on replies? Hire dedicated Filipino support on Australian hours.",
            "We recruit and screen. You interview. Employers hiring - not a customer service job ad.",
            "Virtual customer service staff for Australian businesses. Obligation-free chat.",
            "One support seat that knows your brand. You pick. We handle employment admin.",
        ],
        "why_ctr": "One enabled RSA. Keywords include 'virtual customer service agent' and 'hire customer service virtual assistant'.",
        "why_cvr": "Employer qualification vs job-seeker CS terms. LP already matches.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Customer_Service_Outsource_PH",
        "status": "ready",
        "cluster": "cs_outsource_au",
        "path1": "outsource",
        "path2": "support",
        "headlines": [
            "Outsource Customer Service",
            "Dedicated Support Seat",
            "Philippines Support Staff",
            "Not a Call-Center Bench",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "You Pick the Person",
            "Book a Hiring Consultation",
            "Australian Businesses Only",
            "Same Agent on Your Queue",
            "Employment Admin Handled",
            "Skip Rotating BPO Seats",
            "Support You Can Keep",
            "You Meet Them Before Go-Live",
        ],
        "descriptions": [
            "Outsource customer service to a dedicated Filipino teammate - not a BPO bench.",
            "We recruit and screen. You interview the person. We handle employment admin.",
            "Not a rotating BPO bench. You interview the person who joins your queue.",
            "Book an obligation-free chat. Employers only. One support seat, your hours.",
        ],
        "why_ctr": "52 impressions on 'hire outsourced customer service' but 49 of the ST clicks are the query '24x7 direct'. Need a contrast ad, not more PH jargon.",
        "why_cvr": "If they typed a competitor, the only win is a clearer offer: you interview, Australian hours, dedicated seat.",
        "new_pct": 40,
        "lp": {
            "url": "https://www.virtualcoworker.app/au/customer-service",
            "before_h1": "Customers waiting on replies? Add dedicated Filipino support.",
            "after_h1": "Customers waiting on replies? Add dedicated Filipino support.",
            "before_sub": "Questions sitting in the queue? We shortlist. You interview. Dedicated support on Australian hours - we handle employment admin.",
            "after_sub": "Questions sitting in the queue? We recruit and screen. You interview the person - not a rotating call-center bench. Dedicated Filipino support on Australian hours.",
            "note": "One clause vs BPO-bench shoppers (24x7 Direct queries). No competitor names on the page.",
        },
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Digital_Marketing_Hire_PH",
        "status": "ready",
        "cluster": "marketing",
        "path1": "marketing",
        "path2": "hire",
        "headlines": [
            "Hire a Filipino Marketer",
            "Remote Marketing Assistant",
            "Marketing Virtual Assistant",
            "Marketing Still Slipping?",
            "Dedicated Marketing Seat",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Not a Freelance Marketer",
            "Book a Hiring Consultation",
            "Australian Teams Hiring",
            "Campaigns Need an Owner",
            "You Meet Them First",
            "Employment Admin Handled",
            "Philippines Marketing Hire",
        ],
        "descriptions": [
            "Marketing still slipping? Hire a dedicated Filipino marketer on Australian hours.",
            "Remote marketing assistant for Australian businesses. We recruit. You interview.",
            "Not a freelance marketer. Book an obligation-free chat. Employers only.",
            "Campaigns, reporting, content ops. You pick who joins. We handle employment admin.",
        ],
        "why_ctr": "Tiny sample but keywords match US winner ('remote marketing assistant'). Live ads still say Marketing VA / SEO & Content VA.",
        "why_cvr": "LP already matches. Consultation CTA. Thin volume - directional.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Digital_Marketing_Outsource_PH",
        "status": "ready",
        "cluster": "marketing",
        "path1": "outsource",
        "path2": "marketing",
        "headlines": [
            "Outsource Marketing Ops",
            "Dedicated Filipino Marketer",
            "Philippines Marketing Staff",
            "Not a Melbourne Agency",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Same Marketer Every Day",
            "Book a Hiring Consultation",
            "Australian Brands Only",
            "You Keep Strategy In-House",
            "Employment Admin Handled",
            "Skip Freelance Marketing",
            "Offshore Seat. Your Tools.",
            "You Interview Before Hire",
        ],
        "descriptions": [
            "Outsource marketing ops to a dedicated Filipino marketer - not a local agency retainer.",
            "Dedicated Filipino marketer on your tools. You interview. Australian hours.",
            "Search is leaking to Melbourne/Perth agency queries. This is a person on your team.",
            "Book an obligation-free chat. Employers only. We handle employment admin after you pick.",
        ],
        "why_ctr": "No enabled RSA. Keywords exist ('offshore digital marketing'). Filling the hole with employer-staffing language vs local-agency leakage.",
        "why_cvr": "Clarifies dedicated seat vs PH/Melbourne agency. URL /au/digital-marketing already matches.",
        "new_pct": 40,
        "lp": None,
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Sales_Hire_PH",
        "status": "ready",
        "cluster": "sales",
        "path1": "sales",
        "path2": "hire",
        "headlines": [
            "Hire Sales Support Staff",
            "Virtual Appointment Setter",
            "Filipino Sales Assistant",
            "Dedicated Sales Seat",
            "Follow-Ups Still Slipping?",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Not a Setter Job Ad",
            "Book a Hiring Consultation",
            "Australian Teams Hiring Sales",
            "You Meet Them First",
            "Employment Admin Handled",
            "Skip Freelance Outbound",
            "Pipeline Help That Stays",
        ],
        "descriptions": [
            "Hire a virtual appointment setter - dedicated Filipino staff on Australian hours.",
            "We recruit and screen. You interview. Employers only - not a work-from-home setter ad.",
            "Book an obligation-free chat. CRM, follow-up, booking. You pick who joins.",
            "A sales seat that stays. We handle employment admin after you say yes.",
        ],
        "why_ctr": "One enabled RSA. Keyword 'virtual appointment setter' (13 impr) is unused in the live headlines (Lead Gen Specialist / PH jargon).",
        "why_cvr": "Employer qualification + Australian hours. Sales LP already matches setter language.",
        "new_pct": 35,
        "lp": None,
    },
    {
        "market": "AU",
        "campaign": "VC_AU_S_ROLES",
        "ad_group": "Social_Media_Hire_PH",
        "status": "ready",
        "cluster": "social",
        "path1": "social",
        "path2": "hire",
        "headlines": [
            "Hire Social Media Staff",
            "Virtual Social Media Manager",
            "Filipino Social Teammate",
            "Social Gone Quiet?",
            "Dedicated Social Seat",
            "We Recruit and Screen",
            "Interview Your Shortlist",
            "On Australian Hours",
            "Not a Freelance Poster",
            "Book a Hiring Consultation",
            "Australian Brands Hiring",
            "Scheduling and Community",
            "You Meet Them First",
            "Employment Admin Handled",
            "Philippines Social Support",
        ],
        "descriptions": [
            "Social gone quiet? Hire a dedicated Filipino social teammate on Australian hours.",
            "Virtual social media manager for Australian brands. We recruit. You interview.",
            "Not a freelance poster. Book an obligation-free chat. Employers only.",
            "One social seat that stays. You pick. We handle employment admin.",
        ],
        "why_ctr": "Live ads use SMM/VA jargon and DKI. Keyword 'virtual social media manager' is the one that clicked.",
        "why_cvr": "LP already matches. Spell out the role; keep consultation CTA.",
        "new_pct": 35,
        "lp": None,
    },
]


LEAVE_REASONS: dict[tuple[str, str], dict] = {
    ("US", "Brand_VC"): {
        "status": "leave",
        "why": "Brand is deferred. Do not add RSA challengers here.",
    },
    ("AU", "Brand_VC"): {
        "status": "leave",
        "why": "Brand is deferred. Do not add RSA challengers here.",
    },
    ("US", "Hire_VA_PH"): {
        "status": "leave",
        "why": "Already 3 enabled RSAs. CTR 12.8% launch / 13.5% last two complete days. Do not add a fourth. Future replacement: rewrite paused 'Need an Extra Pair of Hands?' (0 impr) if a winner fades.",
        "replacement_hint": "Paused ad 820821004472 has never served. Use that slot later - do not touch the three enabled winners.",
    },
    ("AU", "Recruitment_Hire_PH"): {
        "status": "leave",
        "why": "Already 3 enabled RSAs. CTR 17.9% on 123 impressions. Leave the set alone this pass.",
        "replacement_hint": "Watch job-seeker leakage ('australia virtual assistant hiring'). Negatives are out of scope here.",
    },
    ("US", "Admin_City_Test"): {
        "status": "leave",
        "why": "Geo test group. 1 enabled RSA already uses city DKI. Not enough clean employer evidence to justify a second RSA this pass.",
    },
    ("AU", "Admin_City_Test"): {
        "status": "leave",
        "why": "Geo test group. Almost no impressions. Leave alone.",
    },
    ("US", "Accounting_Outsource_PH"): {
        "status": "leave",
        "why": "3 impressions, 0 clicks. No converted query. Leave the two enabled RSAs alone.",
    },
    ("AU", "Accounting_Outsource_PH"): {
        "status": "leave",
        "why": "Competitor-brand and local-accountant leakage. 0 clicks on the enabled RSA. Not enough employer evidence.",
    },
    ("US", "Bookkeeping_Outsource_PH"): {
        "status": "leave",
        "why": "2 impressions on the enabled RSA. Outsource bookkeeping terms are not converting. Leave alone.",
    },
    ("AU", "Bookkeeping_Outsource_PH"): {
        "status": "leave",
        "why": "0 clicks. Local bookkeeping-service leakage. Leave alone.",
    },
    ("US", "Human_Resources_Outsource_PH"): {
        "status": "leave",
        "why": "Search terms are competitor brands (Rippling, iPloy). No employer outsource-HR language worth a new RSA.",
    },
    ("AU", "Human_Resources_Hire_PH"): {
        "status": "leave",
        "why": "1 impression. Two enabled RSAs already. Wait for traffic.",
    },
    ("AU", "Human_Resources_Outsource_PH"): {
        "status": "leave",
        "why": "Zero impressions on enabled RSAs. Leave alone.",
    },
    ("US", "Recruitment_Outsource_PH"): {
        "status": "leave",
        "why": "1 impression. Leave alone.",
    },
    ("AU", "Recruitment_Outsource_PH"): {
        "status": "leave",
        "why": "Local recruiter-brand leakage (Adecco). Not a staffing-offer query. Leave alone.",
    },
    ("US", "Sales_Outsource_PH"): {
        "status": "leave",
        "why": "1 impression, no search-term evidence. Leave alone.",
    },
    ("AU", "Sales_Outsource_PH"): {
        "status": "leave",
        "why": "1 impression. Leave alone.",
    },
    ("US", "Social_Media_Outsource_PH"): {
        "status": "leave",
        "why": "Search terms are SMM-panel junk. An RSA cannot fix that. Leave the enabled ad; negatives are a different job.",
    },
    ("AU", "Social_Media_Outsource_PH"): {
        "status": "leave",
        "why": "Local agency / SMM-panel leakage. Thin employer evidence. Leave alone.",
    },
}


COMPETITORS = {
    "staffing_agency": {
        "names": ["MyOutDesk", "Cherry Assistant", "Wing"],
        "summary": "MyOutDesk: Book a Free Strategy Call, hire in 7 days, dedicated VAs, 70% savings claim. Cherry: recruit + shortlist, PH or South Africa, pay if you hire. Wing: managed execution, live in 48 hours, they interview talent for you.",
        "gap": "VC can own Philippines-named dedicated staff + you interview the shortlist + US hours + since 2011. Do not copy 48-hour / 7-day / 70% claims.",
    },
    "hire_va_ph": {
        "names": ["Wing", "MyOutDesk", "Magic"],
        "summary": "Wing: managed VA, not a marketplace, 48 hours, they assess talent. MyOutDesk: strategy call, dedicated, 7 days. Magic: busy-professional concierge VA - weaker employer ICP.",
        "gap": "Name Philippines. Let the employer interview. Dedicated seat, not managed execution theater. No concierge/lifestyle promise.",
    },
    "va_agency": {
        "names": ["Wing", "MyOutDesk", "Magic"],
        "summary": "All three sell 'agency' energy with speed and managed oversight.",
        "gap": "Firm-not-marketplace + you choose who joins. Spell out Virtual Assistant for US (no VA=Virginia).",
    },
    "virtual_staff": {
        "names": ["MyOutDesk", "Cherry Assistant"],
        "summary": "Staffing language, dedicated remote talent, payroll handled.",
        "gap": "Say virtual staff / Philippines-based staff. Keep consultation CTA.",
    },
    "admin_ea": {
        "names": ["Wing", "MyOutDesk", "Belay (not in SERP pack)"],
        "summary": "Inbox/calendar offload, EA products, speed claims.",
        "gap": "Filipino dedicated admin + you interview + $8 only if ops still stands behind the live LP.",
    },
    "accounting": {
        "names": ["MyOutDesk", "local CPA ads"],
        "summary": "Competitors either sell bookkeeping VA or look like licensed firms.",
        "gap": "Accounting support / extra capacity - not CPA. You interview.",
    },
    "bookkeeping": {
        "names": ["MyOutDesk", "Wing"],
        "summary": "Books / invoices / dedicated bookkeeper.",
        "gap": "Filipino bookkeeper, dedicated weekly seat, no ProAdvisor claim.",
    },
    "cs_hire": {
        "names": ["Wing", "MyOutDesk"],
        "summary": "Support roles as managed VA seats.",
        "gap": "Employer hiring support staff - not WFH CS jobs. Same agent, not a bench.",
    },
    "cs_outsource": {
        "names": ["BPO / call-center vendors", "Wing"],
        "summary": "Outsource CS often means a call-center bench.",
        "gap": "Dedicated person you interview vs BPO pit.",
    },
    "cs_outsource_au": {
        "names": ["24x7 Direct", "Outsourcing Angel"],
        "summary": "24x7 Direct dominates AU CS-outsource terms (brand queries). Full-time PH BPO, ISO, they manage. OA: Freedom Audit.",
        "gap": "You interview the agent. Australian hours. Not a rotating bench. Do not claim ISO or 70% labour savings.",
    },
    "marketing": {
        "names": ["Wing", "MyOutDesk", "PH marketing agencies"],
        "summary": "VA marketing seats vs PH agency retainers.",
        "gap": "Remote marketing assistant as a dedicated teammate you interview - not an agency.",
    },
    "sales": {
        "names": ["Wing", "MyOutDesk", "Cherry"],
        "summary": "Setter / SDR products, often mixed with WFH job ads in the auction.",
        "gap": "Employers hiring a setter - not a setter job. You interview.",
    },
    "social": {
        "names": ["Wing", "MyOutDesk", "freelance SMM"],
        "summary": "Social VA vs freelancer posters vs SMM-panel junk.",
        "gap": "Dedicated social teammate, you interview, not freelance posting.",
    },
    "recruiting": {
        "names": ["job boards", "VA job ads"],
        "summary": "This auction is contaminated with job-seeker queries.",
        "gap": "Say employers only / not a jobs board. Recruiting support for TA teams.",
    },
    "hr": {
        "names": ["Wing", "MyOutDesk"],
        "summary": "HR / people-ops VA seats.",
        "gap": "HR virtual assistant for employers. Thin evidence.",
    },
    "staffing_agency_au": {
        "names": ["Outsourcing Angel", "24x7 Direct", "Staffhouse"],
        "summary": "OA: Freedom Audit, 5D system, AU-weighted. 24x7: Melbourne BPO, 70% save, full-time only. Staffhouse appears in terms.",
        "gap": "Filipino staffing agency + you interview + Australian hours + since 2011. No Freedom Audit clone.",
    },
    "hire_va_au": {
        "names": ["24x7 Direct", "Outsourcing Angel"],
        "summary": "AU hire-VA auction is local-BPO heavy. 24x7 and OA show up in search terms.",
        "gap": "Hiring a virtual assistant on Australian hours, you interview, part-time or full-time. Not a 40-hour BPO lock-in.",
    },
    "admin_ea_au": {
        "names": ["24x7 Direct", "My Virtue Desk", "Coconut VA"],
        "summary": "24x7 Direct is the main brand query inside AU admin.",
        "gap": "Virtual admin assistant on Australian hours. You interview. Not a BPO bench.",
    },
}
